/* vocab-data.js — curated review vocabulary for the Korean course (A1–A2 · TOPIK I).

   Consumed by learn.js, glossary.js, readings.js, cando.js and build_anki.py. Keyed by
   lesson number, plus "titles", "slugs" (lesson -> page filename) and "levels" maps.
   Each word is { ko, pron, en, cat? } — pron is Revised Romanization.
   Single source of truth for the review deck, glossary, quizzes and the Anki deck:
   re-run `python3 build_anki.py` after editing. build_anki.py parses this file as
   JSON, so write Hangul literally (no \u escapes) and keep keys double-quoted. */
window.KOREAN_VOCAB = {
  "titles": {
    "1": "Hangul Consonants",
    "2": "Hangul Vowels & Syllable Blocks",
    "3": "Pronunciation Rules",
    "4": "Greetings & Essential Phrases",
    "5": "Sentence Basics: 이에요, 은/는 & 이/가",
    "6": "Numbers, Time & Dates",
    "7": "Verbs & the Polite Present",
    "8": "Family & Personal Descriptions",
    "9": "Particles of Place, Time & People",
    "10": "Negation & Asking Questions",
    "11": "Food & Dining",
    "12": "Home, Household & Daily Routine",
    "13": "Speech Levels & Honorifics",
    "14": "Shopping & Money",
    "15": "The Past Tense",
    "16": "Directions & Transportation",
    "17": "Wants, Plans & the Future",
    "18": "Hobbies & Daily Life",
    "19": "Can, Must & May",
    "20": "Health & Body",
    "21": "Irregular Verbs",
    "22": "Weather & Seasons",
    "23": "Connecting Clauses",
    "24": "Work & Education",
    "25": "Describing: Modifiers & Comparisons",
    "26": "Technology & Communication",
    "27": "Emotions & Relationships",
    "28": "Travel & Korean Culture"
  },
  "slugs": {
    "1": "korean_hangul_consonants",
    "2": "korean_hangul_vowels",
    "3": "korean_pronunciation",
    "4": "korean_greetings_essentials",
    "5": "korean_grammar_sentence_basics",
    "6": "korean_numbers_time_dates",
    "7": "korean_grammar_present_tense",
    "8": "korean_family_descriptions",
    "9": "korean_grammar_particles",
    "10": "korean_grammar_negation_questions",
    "11": "korean_food_dining",
    "12": "korean_home_daily_routine",
    "13": "korean_grammar_speech_levels",
    "14": "korean_shopping_money",
    "15": "korean_grammar_past_tense",
    "16": "korean_directions_transportation",
    "17": "korean_grammar_future_plans",
    "18": "korean_hobbies_daily_life",
    "19": "korean_grammar_modals_requests",
    "20": "korean_health_body",
    "21": "korean_grammar_irregular_verbs",
    "22": "korean_weather_seasons",
    "23": "korean_grammar_connectors",
    "24": "korean_work_education",
    "25": "korean_grammar_modifiers_comparisons",
    "26": "korean_technology_communication",
    "27": "korean_emotions_relationships",
    "28": "korean_travel_culture"
  },
  "levels": {
    "1": "A1",
    "2": "A1",
    "3": "A1",
    "4": "A1",
    "5": "A1",
    "6": "A1",
    "7": "A1",
    "8": "A1",
    "9": "A1",
    "10": "A1",
    "11": "A1",
    "12": "A1",
    "13": "A1–A2",
    "14": "A1",
    "15": "A1–A2",
    "16": "A2",
    "17": "A2",
    "18": "A2",
    "19": "A2",
    "20": "A2",
    "21": "A2",
    "22": "A2",
    "23": "A2",
    "24": "A2",
    "25": "A2",
    "26": "A2",
    "27": "A2",
    "28": "A2"
  },
  "1": [
    {"ko": "한글", "pron": "hangeul", "en": "Hangul, the Korean alphabet", "cat": "Hangul terms"},
    {"ko": "자음", "pron": "jaeum", "en": "consonant", "cat": "Hangul terms"},
    {"ko": "받침", "pron": "batchim", "en": "final consonant of a block", "cat": "Hangul terms"},
    {"ko": "글자", "pron": "geulja", "en": "letter; character", "cat": "Hangul terms"},
    {"ko": "기역", "pron": "giyeok", "en": "the letter ㄱ", "cat": "Letter names"},
    {"ko": "니은", "pron": "nieun", "en": "the letter ㄴ", "cat": "Letter names"},
    {"ko": "디귿", "pron": "digeut", "en": "the letter ㄷ", "cat": "Letter names"},
    {"ko": "리을", "pron": "rieul", "en": "the letter ㄹ", "cat": "Letter names"},
    {"ko": "미음", "pron": "mieum", "en": "the letter ㅁ", "cat": "Letter names"},
    {"ko": "비읍", "pron": "bieup", "en": "the letter ㅂ", "cat": "Letter names"},
    {"ko": "시옷", "pron": "siot", "en": "the letter ㅅ", "cat": "Letter names"},
    {"ko": "이응", "pron": "ieung", "en": "the letter ㅇ", "cat": "Letter names"},
    {"ko": "지읒", "pron": "jieut", "en": "the letter ㅈ", "cat": "Letter names"},
    {"ko": "히읗", "pron": "hieut", "en": "the letter ㅎ", "cat": "Letter names"},
    {"ko": "바다", "pron": "bada", "en": "sea", "cat": "Nouns", "img": "sea"},
    {"ko": "나라", "pron": "nara", "en": "country", "cat": "Nouns"},
    {"ko": "사자", "pron": "saja", "en": "lion", "cat": "Nouns"},
    {"ko": "하마", "pron": "hama", "en": "hippo", "cat": "Nouns"},
    {"ko": "아빠", "pron": "appa", "en": "dad", "cat": "Nouns", "img": "father"},
    {"ko": "차", "pron": "cha", "en": "car; tea", "cat": "Nouns"},
    {"ko": "가방", "pron": "gabang", "en": "bag", "cat": "Nouns", "img": "bag"},
    {"ko": "강", "pron": "gang", "en": "river", "cat": "Nouns"},
    {"ko": "산", "pron": "san", "en": "mountain", "cat": "Nouns", "img": "mountain"},
    {"ko": "밥", "pron": "bap", "en": "cooked rice; meal", "cat": "Nouns", "img": "cooked-rice"},
    {"ko": "방", "pron": "bang", "en": "room", "cat": "Nouns"},
    {"ko": "빵", "pron": "ppang", "en": "bread", "cat": "Nouns", "img": "bread"},
    {"ko": "쌀", "pron": "ssal", "en": "uncooked rice", "cat": "Nouns"},
    {"ko": "달", "pron": "dal", "en": "moon", "cat": "Nouns"},
    {"ko": "탈", "pron": "tal", "en": "mask", "cat": "Nouns"},
    {"ko": "딸", "pron": "ttal", "en": "daughter", "cat": "Nouns", "img": "daughter"},
    {"ko": "발", "pron": "bal", "en": "foot", "cat": "Nouns", "img": "foot"},
    {"ko": "팔", "pron": "pal", "en": "arm", "cat": "Nouns"},
    {"ko": "자다", "pron": "jada", "en": "to sleep", "cat": "Verbs & adjectives"},
    {"ko": "짜다", "pron": "jjada", "en": "to be salty", "cat": "Verbs & adjectives", "img": "salty"},
    {"ko": "사다", "pron": "sada", "en": "to buy", "cat": "Verbs & adjectives"},
    {"ko": "싸다", "pron": "ssada", "en": "to be cheap", "cat": "Verbs & adjectives"}
  ],
  "2": [
    {"ko": "모음", "pron": "moeum", "en": "vowel", "cat": "Hangul terms"},
    {"ko": "아이", "pron": "ai", "en": "child", "cat": "People", "img": "child"},
    {"ko": "어머니", "pron": "eomeoni", "en": "mother", "cat": "People", "img": "mother"},
    {"ko": "아버지", "pron": "abeoji", "en": "father", "cat": "People", "img": "father"},
    {"ko": "여자", "pron": "yeoja", "en": "woman", "cat": "People"},
    {"ko": "의사", "pron": "uisa", "en": "doctor", "cat": "People", "img": "doctor"},
    {"ko": "이름", "pron": "ireum", "en": "name", "cat": "Everyday nouns"},
    {"ko": "야구", "pron": "yagu", "en": "baseball", "cat": "Everyday nouns"},
    {"ko": "오리", "pron": "ori", "en": "duck", "cat": "Everyday nouns"},
    {"ko": "요리", "pron": "yori", "en": "cooking; dish", "cat": "Everyday nouns", "img": "cook"},
    {"ko": "유리", "pron": "yuri", "en": "glass", "cat": "Everyday nouns"},
    {"ko": "개", "pron": "gae", "en": "dog", "cat": "Everyday nouns", "img": "dog"},
    {"ko": "얘기", "pron": "yaegi", "en": "talk; story", "cat": "Everyday nouns"},
    {"ko": "세계", "pron": "segye", "en": "world", "cat": "Everyday nouns"},
    {"ko": "외국", "pron": "oeguk", "en": "foreign country", "cat": "Everyday nouns"},
    {"ko": "원", "pron": "won", "en": "won (currency)", "cat": "Everyday nouns"},
    {"ko": "위", "pron": "wi", "en": "top; above", "cat": "Everyday nouns"},
    {"ko": "의자", "pron": "uija", "en": "chair", "cat": "Everyday nouns", "img": "chair"},
    {"ko": "눈", "pron": "nun", "en": "eye; snow", "cat": "Everyday nouns"},
    {"ko": "한국", "pron": "hanguk", "en": "Korea", "cat": "Everyday nouns"},
    {"ko": "학교", "pron": "hakgyo", "en": "school", "cat": "Everyday nouns", "img": "school"},
    {"ko": "예", "pron": "ye", "en": "yes", "cat": "Short words"},
    {"ko": "왜", "pron": "wae", "en": "why", "cat": "Short words"},
    {"ko": "우유", "pron": "uyu", "en": "milk", "cat": "Food & drink", "img": "milk"},
    {"ko": "음식", "pron": "eumsik", "en": "food", "cat": "Food & drink"},
    {"ko": "과일", "pron": "gwail", "en": "fruit", "cat": "Food & drink", "img": "fruit"},
    {"ko": "김치", "pron": "gimchi", "en": "kimchi", "cat": "Food & drink"},
    {"ko": "물", "pron": "mul", "en": "water", "cat": "Food & drink", "img": "water"},
    {"ko": "커피", "pron": "keopi", "en": "coffee", "cat": "Loanwords", "img": "coffee"},
    {"ko": "바나나", "pron": "banana", "en": "banana", "cat": "Loanwords", "img": "banana"},
    {"ko": "버스", "pron": "beoseu", "en": "bus", "cat": "Loanwords", "img": "bus"},
    {"ko": "택시", "pron": "taeksi", "en": "taxi", "cat": "Loanwords", "img": "taxi"},
    {"ko": "피자", "pron": "pija", "en": "pizza", "cat": "Loanwords"},
    {"ko": "컴퓨터", "pron": "keompyuteo", "en": "computer", "cat": "Loanwords", "img": "computer"}
  ],
  "3": [
    {"ko": "발음", "pron": "bareum", "en": "pronunciation", "cat": "Language terms"},
    {"ko": "한국어", "pron": "hangugeo", "en": "Korean language", "cat": "Language terms"},
    {"ko": "한국말", "pron": "hangungmal", "en": "Korean (spoken language)", "cat": "Language terms"},
    {"ko": "국", "pron": "guk", "en": "soup", "cat": "Food & places"},
    {"ko": "국물", "pron": "gungmul", "en": "broth", "cat": "Food & places"},
    {"ko": "부엌", "pron": "bueok", "en": "kitchen", "cat": "Food & places", "img": "kitchen"},
    {"ko": "밖", "pron": "bak", "en": "outside", "cat": "Food & places"},
    {"ko": "앞", "pron": "ap", "en": "front", "cat": "Food & places"},
    {"ko": "식당", "pron": "sikdang", "en": "restaurant", "cat": "Food & places", "img": "restaurant"},
    {"ko": "입구", "pron": "ipgu", "en": "entrance", "cat": "Food & places"},
    {"ko": "학교", "pron": "hakgyo", "en": "school", "cat": "Food & places", "img": "school"},
    {"ko": "닭", "pron": "dak", "en": "chicken", "cat": "Food & places"},
    {"ko": "맛", "pron": "mat", "en": "taste", "cat": "Everyday nouns"},
    {"ko": "꽃", "pron": "kkot", "en": "flower", "cat": "Everyday nouns", "img": "flower"},
    {"ko": "옷", "pron": "ot", "en": "clothes", "cat": "Everyday nouns", "img": "clothes"},
    {"ko": "값", "pron": "gap", "en": "price", "cat": "Everyday nouns"},
    {"ko": "음악", "pron": "eumak", "en": "music", "cat": "Everyday nouns"},
    {"ko": "설날", "pron": "seollal", "en": "Lunar New Year", "cat": "Everyday nouns"},
    {"ko": "연락", "pron": "yeollak", "en": "contact", "cat": "Everyday nouns"},
    {"ko": "입학", "pron": "iphak", "en": "school admission", "cat": "Everyday nouns"},
    {"ko": "고양이", "pron": "goyangi", "en": "cat", "cat": "Everyday nouns", "img": "cat"},
    {"ko": "여덟", "pron": "yeodeol", "en": "eight", "cat": "Everyday nouns"},
    {"ko": "같이", "pron": "gachi", "en": "together", "cat": "Everyday nouns"},
    {"ko": "먹다", "pron": "meokda", "en": "to eat", "cat": "Verbs & adjectives"},
    {"ko": "읽다", "pron": "ikda", "en": "to read", "cat": "Verbs & adjectives"},
    {"ko": "앉다", "pron": "anda", "en": "to sit", "cat": "Verbs & adjectives"},
    {"ko": "없다", "pron": "eopda", "en": "to not exist; to lack", "cat": "Verbs & adjectives"},
    {"ko": "좋다", "pron": "jota", "en": "to be good", "cat": "Verbs & adjectives", "img": "good"},
    {"ko": "맛있다", "pron": "masitda", "en": "to be delicious", "cat": "Verbs & adjectives", "img": "delicious"},
    {"ko": "감사합니다", "pron": "gamsahamnida", "en": "thank you (formal)", "cat": "Set phrases"},
    {"ko": "좋아요", "pron": "joayo", "en": "it's good; I like it", "cat": "Set phrases"},
    {"ko": "괜찮아요", "pron": "gwaenchanayo", "en": "it's okay", "cat": "Set phrases"},
    {"ko": "축하해요", "pron": "chukahaeyo", "en": "congratulations", "cat": "Set phrases"}
  ],
  "4": [
    {"ko": "안녕하세요", "pron": "annyeonghaseyo", "en": "hello", "cat": "Greetings & goodbyes"},
    {"ko": "안녕하십니까", "pron": "annyeonghasimnikka", "en": "hello (very formal)", "cat": "Greetings & goodbyes"},
    {"ko": "안녕", "pron": "annyeong", "en": "hi; bye (casual)", "cat": "Greetings & goodbyes"},
    {"ko": "안녕히 가세요", "pron": "annyeonghi gaseyo", "en": "goodbye (to one leaving)", "cat": "Greetings & goodbyes"},
    {"ko": "안녕히 계세요", "pron": "annyeonghi gyeseyo", "en": "goodbye (to one staying)", "cat": "Greetings & goodbyes"},
    {"ko": "처음 뵙겠습니다", "pron": "cheoeum boepgetseumnida", "en": "how do you do", "cat": "Greetings & goodbyes"},
    {"ko": "만나서 반갑습니다", "pron": "mannaseo bangapseumnida", "en": "nice to meet you (formal)", "cat": "Greetings & goodbyes"},
    {"ko": "오랜만이에요", "pron": "oraenmanieyo", "en": "long time no see", "cat": "Greetings & goodbyes"},
    {"ko": "잘 지냈어요?", "pron": "jal jinaesseoyo?", "en": "how have you been?", "cat": "Greetings & goodbyes"},
    {"ko": "또 만나요", "pron": "tto mannayo", "en": "see you again", "cat": "Greetings & goodbyes"},
    {"ko": "안녕히 주무세요", "pron": "annyeonghi jumuseyo", "en": "good night (polite)", "cat": "Greetings & goodbyes"},
    {"ko": "잘 자요", "pron": "jal jayo", "en": "good night", "cat": "Greetings & goodbyes"},
    {"ko": "감사합니다", "pron": "gamsahamnida", "en": "thank you (formal)", "cat": "Courtesy phrases"},
    {"ko": "고맙습니다", "pron": "gomapseumnida", "en": "thank you (formal)", "cat": "Courtesy phrases"},
    {"ko": "고마워요", "pron": "gomawoyo", "en": "thank you (informal polite)", "cat": "Courtesy phrases"},
    {"ko": "죄송합니다", "pron": "joesonghamnida", "en": "I'm sorry (formal)", "cat": "Courtesy phrases"},
    {"ko": "미안해요", "pron": "mianhaeyo", "en": "I'm sorry (informal polite)", "cat": "Courtesy phrases"},
    {"ko": "괜찮아요", "pron": "gwaenchanayo", "en": "it's okay; I'm fine", "cat": "Courtesy phrases"},
    {"ko": "실례합니다", "pron": "sillyehamnida", "en": "excuse me", "cat": "Courtesy phrases"},
    {"ko": "저기요", "pron": "jeogiyo", "en": "excuse me! (calling someone)", "cat": "Courtesy phrases"},
    {"ko": "잠깐만요", "pron": "jamkkanmanyo", "en": "just a moment", "cat": "Courtesy phrases"},
    {"ko": "잘 먹겠습니다", "pron": "jal meokgetseumnida", "en": "said before eating", "cat": "Courtesy phrases"},
    {"ko": "잘 먹었습니다", "pron": "jal meogeotseumnida", "en": "said after eating", "cat": "Courtesy phrases"},
    {"ko": "수고하셨습니다", "pron": "sugohasyeotseumnida", "en": "thanks for your hard work", "cat": "Courtesy phrases"},
    {"ko": "잘 부탁드립니다", "pron": "jal butakdeurimnida", "en": "I look forward to working together", "cat": "Courtesy phrases"},
    {"ko": "네", "pron": "ne", "en": "yes", "cat": "Courtesy phrases"},
    {"ko": "아니요", "pron": "aniyo", "en": "no", "cat": "Courtesy phrases"},
    {"ko": "이름이 뭐예요?", "pron": "ireumi mwoyeyo?", "en": "what's your name?", "cat": "Questions"},
    {"ko": "어디에서 왔어요?", "pron": "eodieseo wasseoyo?", "en": "where are you from?", "cat": "Questions"},
    {"ko": "뭐라고요?", "pron": "mworagoyo?", "en": "pardon?", "cat": "Questions"},
    {"ko": "천천히 말해 주세요", "pron": "cheoncheonhi malhae juseyo", "en": "please speak slowly", "cat": "Questions"},
    {"ko": "저", "pron": "jeo", "en": "I; me (polite)", "cat": "People & places"},
    {"ko": "이름", "pron": "ireum", "en": "name", "cat": "People & places"},
    {"ko": "사람", "pron": "saram", "en": "person", "cat": "People & places"},
    {"ko": "학생", "pron": "haksaeng", "en": "student", "cat": "People & places", "img": "student"},
    {"ko": "씨", "pron": "ssi", "en": "Mr./Ms. (after a name)", "cat": "People & places"},
    {"ko": "미국", "pron": "miguk", "en": "USA", "cat": "People & places"},
    {"ko": "일본", "pron": "ilbon", "en": "Japan", "cat": "People & places"},
    {"ko": "중국", "pron": "jungguk", "en": "China", "cat": "People & places"},
    {"ko": "영국", "pron": "yeongguk", "en": "UK", "cat": "People & places"}
  ],
  "5": [
    {"ko": "저", "pron": "jeo", "en": "I / me (polite)", "cat": "People"},
    {"ko": "제", "pron": "je", "en": "my (polite)", "cat": "People"},
    {"ko": "제가", "pron": "jega", "en": "I (as subject)", "cat": "People"},
    {"ko": "사람", "pron": "saram", "en": "person", "cat": "People"},
    {"ko": "학생", "pron": "haksaeng", "en": "student", "cat": "People", "img": "student"},
    {"ko": "선생님", "pron": "seonsaengnim", "en": "teacher", "cat": "People", "img": "teacher"},
    {"ko": "의사", "pron": "uisa", "en": "doctor", "cat": "People", "img": "doctor"},
    {"ko": "회사원", "pron": "hoesawon", "en": "office worker", "cat": "People"},
    {"ko": "친구", "pron": "chingu", "en": "friend", "cat": "People", "img": "friend"},
    {"ko": "저분", "pron": "jeobun", "en": "that person (polite)", "cat": "People"},
    {"ko": "이름", "pron": "ireum", "en": "name", "cat": "Things"},
    {"ko": "책", "pron": "chaek", "en": "book", "cat": "Things", "img": "book"},
    {"ko": "가방", "pron": "gabang", "en": "bag", "cat": "Things", "img": "bag"},
    {"ko": "우산", "pron": "usan", "en": "umbrella", "cat": "Things", "img": "umbrella"},
    {"ko": "물", "pron": "mul", "en": "water", "cat": "Things", "img": "water"},
    {"ko": "커피", "pron": "keopi", "en": "coffee", "cat": "Things", "img": "coffee"},
    {"ko": "차", "pron": "cha", "en": "tea", "cat": "Things"},
    {"ko": "화장실", "pron": "hwajangsil", "en": "restroom", "cat": "Things", "img": "bathroom"},
    {"ko": "이것", "pron": "igeot", "en": "this (thing)", "cat": "Pointing Words"},
    {"ko": "그것", "pron": "geugeot", "en": "that (near you)", "cat": "Pointing Words"},
    {"ko": "저것", "pron": "jeogeot", "en": "that (over there)", "cat": "Pointing Words"},
    {"ko": "이거", "pron": "igeo", "en": "this (spoken)", "cat": "Pointing Words"},
    {"ko": "여기", "pron": "yeogi", "en": "here", "cat": "Pointing Words"},
    {"ko": "거기", "pron": "geogi", "en": "there (near you)", "cat": "Pointing Words"},
    {"ko": "저기", "pron": "jeogi", "en": "over there", "cat": "Pointing Words"},
    {"ko": "뭐", "pron": "mwo", "en": "what", "cat": "Questions & Answers"},
    {"ko": "누구", "pron": "nugu", "en": "who", "cat": "Questions & Answers"},
    {"ko": "누가", "pron": "nuga", "en": "who (as subject)", "cat": "Questions & Answers"},
    {"ko": "어디", "pron": "eodi", "en": "where", "cat": "Questions & Answers"},
    {"ko": "이게 뭐예요?", "pron": "ige mwoyeyo?", "en": "What is this?", "cat": "Questions & Answers"},
    {"ko": "아니에요", "pron": "anieyo", "en": "is not", "cat": "Questions & Answers"},
    {"ko": "있어요", "pron": "isseoyo", "en": "there is / I have", "cat": "Questions & Answers"},
    {"ko": "없어요", "pron": "eopseoyo", "en": "there isn't / I don't have", "cat": "Questions & Answers"}
  ],
  "6": [
    {"ko": "일", "pron": "il", "en": "one (Sino)", "cat": "Sino-Korean"},
    {"ko": "이", "pron": "i", "en": "two (Sino)", "cat": "Sino-Korean"},
    {"ko": "삼", "pron": "sam", "en": "three (Sino)", "cat": "Sino-Korean"},
    {"ko": "십", "pron": "sip", "en": "ten (Sino)", "cat": "Sino-Korean"},
    {"ko": "백", "pron": "baek", "en": "hundred", "cat": "Sino-Korean"},
    {"ko": "천", "pron": "cheon", "en": "thousand", "cat": "Sino-Korean"},
    {"ko": "만", "pron": "man", "en": "ten thousand", "cat": "Sino-Korean"},
    {"ko": "공", "pron": "gong", "en": "zero (reading digits)", "cat": "Sino-Korean"},
    {"ko": "하나", "pron": "hana", "en": "one (Native)", "cat": "Native Korean"},
    {"ko": "둘", "pron": "dul", "en": "two (Native)", "cat": "Native Korean"},
    {"ko": "셋", "pron": "set", "en": "three (Native)", "cat": "Native Korean"},
    {"ko": "넷", "pron": "net", "en": "four (Native)", "cat": "Native Korean"},
    {"ko": "다섯", "pron": "daseot", "en": "five (Native)", "cat": "Native Korean"},
    {"ko": "열", "pron": "yeol", "en": "ten (Native)", "cat": "Native Korean"},
    {"ko": "스물", "pron": "seumul", "en": "twenty (Native)", "cat": "Native Korean"},
    {"ko": "개", "pron": "gae", "en": "counter: things", "cat": "Counters", "img": "dog"},
    {"ko": "명", "pron": "myeong", "en": "counter: people", "cat": "Counters"},
    {"ko": "마리", "pron": "mari", "en": "counter: animals", "cat": "Counters"},
    {"ko": "잔", "pron": "jan", "en": "counter: cups, glasses", "cat": "Counters"},
    {"ko": "권", "pron": "gwon", "en": "counter: books", "cat": "Counters"},
    {"ko": "살", "pron": "sal", "en": "years old", "cat": "Counters"},
    {"ko": "번", "pron": "beon", "en": "times; number (No.)", "cat": "Counters"},
    {"ko": "원", "pron": "won", "en": "won (currency)", "cat": "Counters"},
    {"ko": "시", "pron": "si", "en": "o'clock", "cat": "Time & Dates"},
    {"ko": "분", "pron": "bun", "en": "minute", "cat": "Time & Dates"},
    {"ko": "시간", "pron": "sigan", "en": "hour (duration); time", "cat": "Time & Dates"},
    {"ko": "반", "pron": "ban", "en": "half (past)", "cat": "Time & Dates"},
    {"ko": "오전", "pron": "ojeon", "en": "AM, morning", "cat": "Time & Dates"},
    {"ko": "오후", "pron": "ohu", "en": "PM, afternoon", "cat": "Time & Dates"},
    {"ko": "오늘", "pron": "oneul", "en": "today", "cat": "Time & Dates"},
    {"ko": "내일", "pron": "naeil", "en": "tomorrow", "cat": "Time & Dates"},
    {"ko": "요일", "pron": "yoil", "en": "day of the week", "cat": "Time & Dates"},
    {"ko": "월요일", "pron": "woryoil", "en": "Monday", "cat": "Time & Dates"},
    {"ko": "생일", "pron": "saengil", "en": "birthday", "cat": "Time & Dates"},
    {"ko": "몇 시예요?", "pron": "myeot siyeyo?", "en": "What time is it?", "cat": "Time & Dates"},
    {"ko": "며칠", "pron": "myeochil", "en": "what date; a few days", "cat": "Time & Dates"}
  ],
  "7": [
    {"ko": "가다", "pron": "gada", "en": "to go", "cat": "Verbs"},
    {"ko": "오다", "pron": "oda", "en": "to come", "cat": "Verbs"},
    {"ko": "보다", "pron": "boda", "en": "to see / to watch", "cat": "Verbs"},
    {"ko": "먹다", "pron": "meokda", "en": "to eat", "cat": "Verbs"},
    {"ko": "마시다", "pron": "masida", "en": "to drink", "cat": "Verbs", "img": "drink"},
    {"ko": "자다", "pron": "jada", "en": "to sleep", "cat": "Verbs"},
    {"ko": "사다", "pron": "sada", "en": "to buy", "cat": "Verbs"},
    {"ko": "만나다", "pron": "mannada", "en": "to meet", "cat": "Verbs"},
    {"ko": "읽다", "pron": "ikda", "en": "to read", "cat": "Verbs"},
    {"ko": "앉다", "pron": "anda", "en": "to sit", "cat": "Verbs"},
    {"ko": "배우다", "pron": "baeuda", "en": "to learn", "cat": "Verbs"},
    {"ko": "주다", "pron": "juda", "en": "to give", "cat": "Verbs"},
    {"ko": "기다리다", "pron": "gidarida", "en": "to wait", "cat": "Verbs"},
    {"ko": "받다", "pron": "batda", "en": "to receive", "cat": "Verbs"},
    {"ko": "살다", "pron": "salda", "en": "to live", "cat": "Verbs"},
    {"ko": "알다", "pron": "alda", "en": "to know", "cat": "Verbs"},
    {"ko": "가르치다", "pron": "gareuchida", "en": "to teach", "cat": "Verbs"},
    {"ko": "하다", "pron": "hada", "en": "to do", "cat": "하다 Verbs"},
    {"ko": "공부하다", "pron": "gongbuhada", "en": "to study", "cat": "하다 Verbs"},
    {"ko": "일하다", "pron": "ilhada", "en": "to work", "cat": "하다 Verbs"},
    {"ko": "운동하다", "pron": "undonghada", "en": "to exercise", "cat": "하다 Verbs"},
    {"ko": "좋아하다", "pron": "joahada", "en": "to like", "cat": "하다 Verbs"},
    {"ko": "좋다", "pron": "jota", "en": "to be good", "cat": "Descriptive Verbs", "img": "good"},
    {"ko": "싸다", "pron": "ssada", "en": "to be cheap", "cat": "Descriptive Verbs"},
    {"ko": "비싸다", "pron": "bissada", "en": "to be expensive", "cat": "Descriptive Verbs", "img": "expensive"},
    {"ko": "작다", "pron": "jakda", "en": "to be small", "cat": "Descriptive Verbs", "img": "small"},
    {"ko": "많다", "pron": "manta", "en": "to be many / a lot", "cat": "Descriptive Verbs"},
    {"ko": "멀다", "pron": "meolda", "en": "to be far", "cat": "Descriptive Verbs", "img": "far"},
    {"ko": "괜찮다", "pron": "gwaenchanta", "en": "to be okay", "cat": "Descriptive Verbs"},
    {"ko": "맛있다", "pron": "masitda", "en": "to be delicious", "cat": "Descriptive Verbs", "img": "delicious"},
    {"ko": "재미있다", "pron": "jaemiitda", "en": "to be fun", "cat": "Descriptive Verbs"},
    {"ko": "피곤하다", "pron": "pigonhada", "en": "to be tired", "cat": "Descriptive Verbs"},
    {"ko": "밥", "pron": "bap", "en": "rice / meal", "cat": "Objects", "img": "cooked-rice"},
    {"ko": "영화", "pron": "yeonghwa", "en": "movie", "cat": "Objects"},
    {"ko": "한국어", "pron": "hangugeo", "en": "Korean (language)", "cat": "Objects"},
    {"ko": "숙제", "pron": "sukje", "en": "homework", "cat": "Objects"}
  ],
  "8": [
    {"ko": "가족", "pron": "gajok", "en": "family", "cat": "Family", "img": "family"},
    {"ko": "아버지", "pron": "abeoji", "en": "father", "cat": "Family", "img": "father"},
    {"ko": "어머니", "pron": "eomeoni", "en": "mother", "cat": "Family", "img": "mother"},
    {"ko": "아빠", "pron": "appa", "en": "dad", "cat": "Family", "img": "father"},
    {"ko": "엄마", "pron": "eomma", "en": "mom", "cat": "Family"},
    {"ko": "부모님", "pron": "bumonim", "en": "parents", "cat": "Family", "img": "parents"},
    {"ko": "형", "pron": "hyeong", "en": "older brother (male speaker)", "cat": "Siblings", "img": "older-brother"},
    {"ko": "오빠", "pron": "oppa", "en": "older brother (female speaker)", "cat": "Siblings", "img": "older-brother"},
    {"ko": "누나", "pron": "nuna", "en": "older sister (male speaker)", "cat": "Siblings", "img": "older-sister"},
    {"ko": "언니", "pron": "eonni", "en": "older sister (female speaker)", "cat": "Siblings", "img": "older-sister"},
    {"ko": "동생", "pron": "dongsaeng", "en": "younger sibling", "cat": "Siblings"},
    {"ko": "남동생", "pron": "namdongsaeng", "en": "younger brother", "cat": "Siblings"},
    {"ko": "여동생", "pron": "yeodongsaeng", "en": "younger sister", "cat": "Siblings"},
    {"ko": "외동", "pron": "oedong", "en": "only child", "cat": "Siblings"},
    {"ko": "할아버지", "pron": "harabeoji", "en": "grandfather", "cat": "Family", "img": "grandfather"},
    {"ko": "할머니", "pron": "halmeoni", "en": "grandmother", "cat": "Family", "img": "grandmother"},
    {"ko": "남편", "pron": "nampyeon", "en": "husband", "cat": "Family"},
    {"ko": "아내", "pron": "anae", "en": "wife", "cat": "Family"},
    {"ko": "아들", "pron": "adeul", "en": "son", "cat": "Family", "img": "son"},
    {"ko": "딸", "pron": "ttal", "en": "daughter", "cat": "Family", "img": "daughter"},
    {"ko": "이모", "pron": "imo", "en": "aunt (mother's sister)", "cat": "Extended family", "img": "aunt"},
    {"ko": "고모", "pron": "gomo", "en": "aunt (father's sister)", "cat": "Extended family", "img": "aunt"},
    {"ko": "삼촌", "pron": "samchon", "en": "uncle (father's brother)", "cat": "Extended family", "img": "uncle"},
    {"ko": "외삼촌", "pron": "oesamchon", "en": "uncle (mother's brother)", "cat": "Extended family", "img": "uncle"},
    {"ko": "사촌", "pron": "sachon", "en": "cousin", "cat": "Extended family"},
    {"ko": "우리", "pron": "uri", "en": "our; my (family)", "cat": "Family"},
    {"ko": "키", "pron": "ki", "en": "height", "cat": "Describing people"},
    {"ko": "크다", "pron": "keuda", "en": "to be big / tall", "cat": "Describing people", "img": "big"},
    {"ko": "작다", "pron": "jakda", "en": "to be small / short", "cat": "Describing people"},
    {"ko": "예쁘다", "pron": "yeppeuda", "en": "to be pretty", "cat": "Describing people"},
    {"ko": "잘생기다", "pron": "jalsaenggida", "en": "to be handsome", "cat": "Describing people"},
    {"ko": "친절하다", "pron": "chinjeolhada", "en": "to be kind", "cat": "Describing people", "img": "kind"},
    {"ko": "재미있다", "pron": "jaemiitda", "en": "to be fun / funny", "cat": "Describing people"},
    {"ko": "똑똑하다", "pron": "ttokttokada", "en": "to be smart", "cat": "Describing people", "img": "smart"},
    {"ko": "젊다", "pron": "jeomda", "en": "to be young", "cat": "Describing people"},
    {"ko": "바쁘다", "pron": "bappeuda", "en": "to be busy", "cat": "Describing people"},
    {"ko": "착하다", "pron": "chakada", "en": "to be good-natured", "cat": "Describing people"}
  ],
  "9": [
    {"ko": "학교", "pron": "hakgyo", "en": "school", "cat": "Places", "img": "school"},
    {"ko": "집", "pron": "jip", "en": "home, house", "cat": "Places", "img": "house"},
    {"ko": "도서관", "pron": "doseogwan", "en": "library", "cat": "Places"},
    {"ko": "식당", "pron": "sikdang", "en": "restaurant", "cat": "Places", "img": "restaurant"},
    {"ko": "회사", "pron": "hoesa", "en": "company, office", "cat": "Places", "img": "office"},
    {"ko": "카페", "pron": "kape", "en": "café", "cat": "Places"},
    {"ko": "은행", "pron": "eunhaeng", "en": "bank", "cat": "Places", "img": "bank"},
    {"ko": "병원", "pron": "byeongwon", "en": "hospital", "cat": "Places", "img": "hospital"},
    {"ko": "편의점", "pron": "pyeonuijeom", "en": "convenience store", "cat": "Places"},
    {"ko": "화장실", "pron": "hwajangsil", "en": "restroom", "cat": "Places", "img": "bathroom"},
    {"ko": "방", "pron": "bang", "en": "room", "cat": "Places"},
    {"ko": "위", "pron": "wi", "en": "on, above", "cat": "Positions"},
    {"ko": "아래", "pron": "arae", "en": "below, under", "cat": "Positions"},
    {"ko": "밑", "pron": "mit", "en": "under, beneath", "cat": "Positions"},
    {"ko": "앞", "pron": "ap", "en": "front, in front of", "cat": "Positions"},
    {"ko": "뒤", "pron": "dwi", "en": "back, behind", "cat": "Positions"},
    {"ko": "옆", "pron": "yeop", "en": "side, next to", "cat": "Positions"},
    {"ko": "안", "pron": "an", "en": "inside", "cat": "Positions"},
    {"ko": "밖", "pron": "bak", "en": "outside", "cat": "Positions"},
    {"ko": "책상", "pron": "chaeksang", "en": "desk", "cat": "Things", "img": "desk"},
    {"ko": "의자", "pron": "uija", "en": "chair", "cat": "Things", "img": "chair"},
    {"ko": "가방", "pron": "gabang", "en": "bag", "cat": "Things", "img": "bag"},
    {"ko": "지갑", "pron": "jigap", "en": "wallet", "cat": "Things"},
    {"ko": "선물", "pron": "seonmul", "en": "present, gift", "cat": "Things"},
    {"ko": "있다", "pron": "itda", "en": "to exist, to have", "cat": "Verbs"},
    {"ko": "없다", "pron": "eopda", "en": "to not exist, not have", "cat": "Verbs"},
    {"ko": "만나다", "pron": "mannada", "en": "to meet", "cat": "Verbs"},
    {"ko": "주다", "pron": "juda", "en": "to give", "cat": "Verbs"},
    {"ko": "받다", "pron": "batda", "en": "to receive", "cat": "Verbs"},
    {"ko": "보내다", "pron": "bonaeda", "en": "to send", "cat": "Verbs"},
    {"ko": "전화하다", "pron": "jeonhwahada", "en": "to phone, to call", "cat": "Verbs"},
    {"ko": "일하다", "pron": "ilhada", "en": "to work", "cat": "Verbs"},
    {"ko": "아침", "pron": "achim", "en": "morning", "cat": "Time & Company"},
    {"ko": "저녁", "pron": "jeonyeok", "en": "evening", "cat": "Time & Company"},
    {"ko": "주말", "pron": "jumal", "en": "weekend", "cat": "Time & Company"},
    {"ko": "같이", "pron": "gachi", "en": "together", "cat": "Time & Company"}
  ],
  "10": [
    {"ko": "안", "pron": "an", "en": "not, don't", "cat": "Negation"},
    {"ko": "못", "pron": "mot", "en": "can't, unable to", "cat": "Negation"},
    {"ko": "없다", "pron": "eopda", "en": "to not exist, not have", "cat": "Negation"},
    {"ko": "모르다", "pron": "moreuda", "en": "to not know", "cat": "Negation"},
    {"ko": "맛없다", "pron": "madeopda", "en": "to taste bad", "cat": "Negation"},
    {"ko": "재미없다", "pron": "jaemieopda", "en": "to be boring", "cat": "Negation"},
    {"ko": "뭐", "pron": "mwo", "en": "what", "cat": "Question Words"},
    {"ko": "무엇", "pron": "mueot", "en": "what (formal)", "cat": "Question Words"},
    {"ko": "누구", "pron": "nugu", "en": "who, whom", "cat": "Question Words"},
    {"ko": "누가", "pron": "nuga", "en": "who (as subject)", "cat": "Question Words"},
    {"ko": "어디", "pron": "eodi", "en": "where", "cat": "Question Words"},
    {"ko": "언제", "pron": "eonje", "en": "when", "cat": "Question Words"},
    {"ko": "왜", "pron": "wae", "en": "why", "cat": "Question Words"},
    {"ko": "어떻게", "pron": "eotteoke", "en": "how", "cat": "Question Words"},
    {"ko": "몇", "pron": "myeot", "en": "how many, what number", "cat": "Question Words"},
    {"ko": "얼마", "pron": "eolma", "en": "how much (price)", "cat": "Question Words"},
    {"ko": "무슨", "pron": "museun", "en": "what (kind of)", "cat": "Question Words"},
    {"ko": "어느", "pron": "eoneu", "en": "which", "cat": "Question Words"},
    {"ko": "어떤", "pron": "eotteon", "en": "what kind of", "cat": "Question Words"},
    {"ko": "네", "pron": "ne", "en": "yes, that's right", "cat": "Answers & Phrases"},
    {"ko": "아니요", "pron": "aniyo", "en": "no, that's not right", "cat": "Answers & Phrases"},
    {"ko": "몰라요", "pron": "mollayo", "en": "I don't know", "cat": "Answers & Phrases"},
    {"ko": "왜요?", "pron": "waeyo?", "en": "Why? Why do you ask?", "cat": "Answers & Phrases"},
    {"ko": "미안해요", "pron": "mianhaeyo", "en": "I'm sorry", "cat": "Answers & Phrases"},
    {"ko": "어때요?", "pron": "eottaeyo?", "en": "How is it? How about…?", "cat": "Answers & Phrases"},
    {"ko": "알다", "pron": "alda", "en": "to know", "cat": "Verbs & Adjectives"},
    {"ko": "좋아하다", "pron": "joahada", "en": "to like", "cat": "Verbs & Adjectives"},
    {"ko": "운동하다", "pron": "undonghada", "en": "to exercise", "cat": "Verbs & Adjectives"},
    {"ko": "요리하다", "pron": "yorihada", "en": "to cook", "cat": "Verbs & Adjectives", "img": "cook"},
    {"ko": "운전하다", "pron": "unjeonhada", "en": "to drive", "cat": "Verbs & Adjectives"},
    {"ko": "비싸다", "pron": "bissada", "en": "to be expensive", "cat": "Verbs & Adjectives", "img": "expensive"},
    {"ko": "피곤하다", "pron": "pigonhada", "en": "to be tired", "cat": "Verbs & Adjectives"},
    {"ko": "숙제", "pron": "sukje", "en": "homework", "cat": "Verbs & Adjectives"},
    {"ko": "술", "pron": "sul", "en": "alcohol", "cat": "Verbs & Adjectives"}
  ],
  "11": [
    {"ko": "밥", "pron": "bap", "en": "cooked rice; meal", "cat": "Food", "img": "cooked-rice"},
    {"ko": "국", "pron": "guk", "en": "soup", "cat": "Food"},
    {"ko": "찌개", "pron": "jjigae", "en": "stew", "cat": "Food"},
    {"ko": "반찬", "pron": "banchan", "en": "side dishes", "cat": "Food"},
    {"ko": "김치", "pron": "gimchi", "en": "kimchi", "cat": "Food"},
    {"ko": "고기", "pron": "gogi", "en": "meat", "cat": "Food", "img": "meat"},
    {"ko": "소고기", "pron": "sogogi", "en": "beef", "cat": "Food"},
    {"ko": "돼지고기", "pron": "dwaejigogi", "en": "pork", "cat": "Food"},
    {"ko": "닭고기", "pron": "dakgogi", "en": "chicken (meat)", "cat": "Food", "img": "chicken"},
    {"ko": "생선", "pron": "saengseon", "en": "fish (food)", "cat": "Food", "img": "fish"},
    {"ko": "해산물", "pron": "haesanmul", "en": "seafood", "cat": "Food"},
    {"ko": "채소", "pron": "chaeso", "en": "vegetables", "cat": "Food"},
    {"ko": "물", "pron": "mul", "en": "water", "cat": "Food", "img": "water"},
    {"ko": "술", "pron": "sul", "en": "alcohol", "cat": "Food"},
    {"ko": "비빔밥", "pron": "bibimbap", "en": "mixed rice bowl", "cat": "Dishes"},
    {"ko": "불고기", "pron": "bulgogi", "en": "marinated grilled beef", "cat": "Dishes"},
    {"ko": "삼겹살", "pron": "samgyeopsal", "en": "grilled pork belly", "cat": "Dishes"},
    {"ko": "떡볶이", "pron": "tteokbokki", "en": "spicy rice cakes", "cat": "Dishes"},
    {"ko": "김밥", "pron": "gimbap", "en": "seaweed rice roll", "cat": "Dishes"},
    {"ko": "식당", "pron": "sikdang", "en": "restaurant", "cat": "At the restaurant", "img": "restaurant"},
    {"ko": "숟가락", "pron": "sutgarak", "en": "spoon", "cat": "At the restaurant"},
    {"ko": "젓가락", "pron": "jeotgarak", "en": "chopsticks", "cat": "At the restaurant"},
    {"ko": "인분", "pron": "inbun", "en": "serving, portion (counter)", "cat": "At the restaurant"},
    {"ko": "저기요!", "pron": "jeogiyo!", "en": "Excuse me! (calling staff)", "cat": "At the restaurant"},
    {"ko": "주세요", "pron": "juseyo", "en": "please give me", "cat": "At the restaurant"},
    {"ko": "계산해 주세요", "pron": "gyesanhae juseyo", "en": "the bill, please", "cat": "At the restaurant", "img": "bill"},
    {"ko": "잘 먹겠습니다", "pron": "jal meokgetseumnida", "en": "said before eating", "cat": "At the restaurant"},
    {"ko": "잘 먹었습니다", "pron": "jal meogeotseumnida", "en": "said after eating", "cat": "At the restaurant"},
    {"ko": "배불러요", "pron": "baebulleoyo", "en": "I'm full", "cat": "At the restaurant"},
    {"ko": "먹다", "pron": "meokda", "en": "to eat", "cat": "Taste & actions"},
    {"ko": "마시다", "pron": "masida", "en": "to drink", "cat": "Taste & actions", "img": "drink"},
    {"ko": "맛있다", "pron": "masitda", "en": "to be delicious", "cat": "Taste & actions", "img": "delicious"},
    {"ko": "맛없다", "pron": "madeopda", "en": "to be not tasty", "cat": "Taste & actions"},
    {"ko": "맵다", "pron": "maepda", "en": "to be spicy", "cat": "Taste & actions", "img": "spicy"},
    {"ko": "달다", "pron": "dalda", "en": "to be sweet", "cat": "Taste & actions", "img": "sweet"},
    {"ko": "짜다", "pron": "jjada", "en": "to be salty", "cat": "Taste & actions", "img": "salty"},
    {"ko": "싱겁다", "pron": "sing-geopda", "en": "to be bland", "cat": "Taste & actions"}
  ],
  "12": [
    {"ko": "집", "pron": "jip", "en": "home, house", "cat": "Housing", "img": "house"},
    {"ko": "아파트", "pron": "apateu", "en": "high-rise apartment", "cat": "Housing"},
    {"ko": "빌라", "pron": "billa", "en": "low-rise block of flats", "cat": "Housing"},
    {"ko": "원룸", "pron": "wollum", "en": "studio flat", "cat": "Housing"},
    {"ko": "오피스텔", "pron": "opiseutel", "en": "officetel studio", "cat": "Housing"},
    {"ko": "주택", "pron": "jutaek", "en": "house", "cat": "Housing", "img": "house"},
    {"ko": "전세", "pron": "jeonse", "en": "lump-sum deposit lease", "cat": "Housing"},
    {"ko": "월세", "pron": "wolse", "en": "monthly rent", "cat": "Housing"},
    {"ko": "방", "pron": "bang", "en": "room", "cat": "Rooms"},
    {"ko": "거실", "pron": "geosil", "en": "living room", "cat": "Rooms", "img": "living-room"},
    {"ko": "부엌", "pron": "bueok", "en": "kitchen", "cat": "Rooms", "img": "kitchen"},
    {"ko": "화장실", "pron": "hwajangsil", "en": "bathroom, toilet", "cat": "Rooms", "img": "bathroom"},
    {"ko": "현관", "pron": "hyeongwan", "en": "entryway", "cat": "Rooms"},
    {"ko": "창문", "pron": "changmun", "en": "window", "cat": "Rooms", "img": "window"},
    {"ko": "침대", "pron": "chimdae", "en": "bed", "cat": "Furniture & Appliances", "img": "bed"},
    {"ko": "책상", "pron": "chaeksang", "en": "desk", "cat": "Furniture & Appliances", "img": "desk"},
    {"ko": "의자", "pron": "uija", "en": "chair", "cat": "Furniture & Appliances", "img": "chair"},
    {"ko": "소파", "pron": "sopa", "en": "sofa", "cat": "Furniture & Appliances", "img": "sofa"},
    {"ko": "식탁", "pron": "siktak", "en": "dining table", "cat": "Furniture & Appliances"},
    {"ko": "옷장", "pron": "otjang", "en": "wardrobe", "cat": "Furniture & Appliances", "img": "wardrobe"},
    {"ko": "냉장고", "pron": "naengjanggo", "en": "refrigerator", "cat": "Furniture & Appliances"},
    {"ko": "세탁기", "pron": "setakgi", "en": "washing machine", "cat": "Furniture & Appliances"},
    {"ko": "이불", "pron": "ibul", "en": "duvet, bedding", "cat": "Furniture & Appliances"},
    {"ko": "청소하다", "pron": "cheongsohada", "en": "to clean", "cat": "Chores"},
    {"ko": "빨래하다", "pron": "ppallaehada", "en": "to do laundry", "cat": "Chores"},
    {"ko": "설거지하다", "pron": "seolgeojihada", "en": "to wash the dishes", "cat": "Chores", "img": "wash-the-dishes"},
    {"ko": "요리하다", "pron": "yorihada", "en": "to cook", "cat": "Chores", "img": "cook"},
    {"ko": "정리하다", "pron": "jeongnihada", "en": "to tidy up", "cat": "Chores"},
    {"ko": "쓰레기를 버리다", "pron": "sseuregireul beorida", "en": "to take out the trash", "cat": "Chores", "img": "take-out-the-trash"},
    {"ko": "분리수거", "pron": "bullisugeo", "en": "sorting recycling", "cat": "Chores"},
    {"ko": "일어나다", "pron": "ireonada", "en": "to get up", "cat": "Daily Routine"},
    {"ko": "씻다", "pron": "ssitda", "en": "to wash (oneself)", "cat": "Daily Routine"},
    {"ko": "샤워하다", "pron": "syawohada", "en": "to shower", "cat": "Daily Routine", "img": "shower"},
    {"ko": "이를 닦다", "pron": "ireul dakda", "en": "to brush one's teeth", "cat": "Daily Routine"},
    {"ko": "옷을 입다", "pron": "oseul ipda", "en": "to get dressed", "cat": "Daily Routine"},
    {"ko": "출근하다", "pron": "chulgeunhada", "en": "to go to work", "cat": "Daily Routine"},
    {"ko": "퇴근하다", "pron": "toegeunhada", "en": "to leave work", "cat": "Daily Routine"},
    {"ko": "자다", "pron": "jada", "en": "to sleep", "cat": "Daily Routine"}
  ],
  "13": [
    {"ko": "안녕하십니까", "pron": "annyeonghasimnikka", "en": "hello (formal)", "cat": "Set Phrases"},
    {"ko": "처음 뵙겠습니다", "pron": "cheoeum boepgetseumnida", "en": "nice to meet you (formal)", "cat": "Set Phrases"},
    {"ko": "반갑습니다", "pron": "bangapseumnida", "en": "pleased to meet you", "cat": "Set Phrases"},
    {"ko": "안녕히 주무세요", "pron": "annyeonghi jumuseyo", "en": "good night (honorific)", "cat": "Set Phrases"},
    {"ko": "성함이 어떻게 되세요?", "pron": "seonghami eotteoke doeseyo?", "en": "may I ask your name?", "cat": "Set Phrases"},
    {"ko": "연세가 어떻게 되세요?", "pron": "yeonsega eotteoke doeseyo?", "en": "may I ask your age?", "cat": "Set Phrases"},
    {"ko": "몇 분이세요?", "pron": "myeot buniseyo?", "en": "how many people?", "cat": "Set Phrases"},
    {"ko": "말 편하게 하세요", "pron": "mal pyeonhage haseyo", "en": "feel free to speak casually", "cat": "Set Phrases"},
    {"ko": "계시다", "pron": "gyesida", "en": "to be (somewhere), honorific", "cat": "Honorific & Humble Verbs"},
    {"ko": "드시다", "pron": "deusida", "en": "to eat/drink, honorific", "cat": "Honorific & Humble Verbs"},
    {"ko": "잡수시다", "pron": "japsusida", "en": "to eat, very honorific", "cat": "Honorific & Humble Verbs"},
    {"ko": "주무시다", "pron": "jumusida", "en": "to sleep, honorific", "cat": "Honorific & Humble Verbs"},
    {"ko": "말씀하시다", "pron": "malsseumhasida", "en": "to speak, honorific", "cat": "Honorific & Humble Verbs"},
    {"ko": "편찮으시다", "pron": "pyeonchaneusida", "en": "to be ill, honorific", "cat": "Honorific & Humble Verbs"},
    {"ko": "돌아가시다", "pron": "doragasida", "en": "to pass away", "cat": "Honorific & Humble Verbs"},
    {"ko": "드리다", "pron": "deurida", "en": "to give, humble", "cat": "Honorific & Humble Verbs"},
    {"ko": "뵙다", "pron": "boepda", "en": "to see/meet, humble", "cat": "Honorific & Humble Verbs"},
    {"ko": "여쭤보다", "pron": "yeojjwoboda", "en": "to ask, humble", "cat": "Honorific & Humble Verbs"},
    {"ko": "말씀드리다", "pron": "malsseumdeurida", "en": "to tell, humble", "cat": "Honorific & Humble Verbs"},
    {"ko": "모시다", "pron": "mosida", "en": "to accompany/serve, humble", "cat": "Honorific & Humble Verbs"},
    {"ko": "성함", "pron": "seongham", "en": "name, honorific", "cat": "Honorific Nouns & Particles"},
    {"ko": "연세", "pron": "yeonse", "en": "age, honorific", "cat": "Honorific Nouns & Particles"},
    {"ko": "댁", "pron": "daek", "en": "home, honorific", "cat": "Honorific Nouns & Particles"},
    {"ko": "진지", "pron": "jinji", "en": "meal, honorific", "cat": "Honorific Nouns & Particles"},
    {"ko": "생신", "pron": "saengsin", "en": "birthday, honorific", "cat": "Honorific Nouns & Particles"},
    {"ko": "말씀", "pron": "malsseum", "en": "words, speech (hon./humble)", "cat": "Honorific Nouns & Particles"},
    {"ko": "분", "pron": "bun", "en": "person, honorific", "cat": "Honorific Nouns & Particles"},
    {"ko": "께서", "pron": "kkeseo", "en": "subject particle, honorific", "cat": "Honorific Nouns & Particles"},
    {"ko": "께", "pron": "kke", "en": "to (someone), honorific", "cat": "Honorific Nouns & Particles"},
    {"ko": "저희", "pron": "jeohui", "en": "we, our (humble)", "cat": "Honorific Nouns & Particles"},
    {"ko": "존댓말", "pron": "jondaenmal", "en": "polite/honorific speech", "cat": "Speech & Relationships"},
    {"ko": "반말", "pron": "banmal", "en": "casual speech", "cat": "Speech & Relationships"},
    {"ko": "선배", "pron": "seonbae", "en": "senior (school, work)", "cat": "Speech & Relationships"},
    {"ko": "후배", "pron": "hubae", "en": "junior (school, work)", "cat": "Speech & Relationships"},
    {"ko": "동갑", "pron": "donggap", "en": "same age", "cat": "Speech & Relationships"},
    {"ko": "교수님", "pron": "gyosunim", "en": "professor", "cat": "Speech & Relationships"},
    {"ko": "사장님", "pron": "sajangnim", "en": "company president, boss", "cat": "Speech & Relationships"},
    {"ko": "나", "pron": "na", "en": "I (casual)", "cat": "Speech & Relationships"},
    {"ko": "너", "pron": "neo", "en": "you (casual)", "cat": "Speech & Relationships"}
  ],
  "14": [
    {"ko": "원", "pron": "won", "en": "won (currency)", "cat": "Money"},
    {"ko": "천 원", "pron": "cheon won", "en": "1,000 won", "cat": "Money"},
    {"ko": "만 원", "pron": "man won", "en": "10,000 won", "cat": "Money"},
    {"ko": "얼마예요?", "pron": "eolmayeyo?", "en": "How much is it?", "cat": "Money"},
    {"ko": "카드", "pron": "kadeu", "en": "card (credit/debit)", "cat": "Money"},
    {"ko": "현금", "pron": "hyeongeum", "en": "cash", "cat": "Money"},
    {"ko": "영수증", "pron": "yeongsujeung", "en": "receipt", "cat": "Money"},
    {"ko": "할인", "pron": "harin", "en": "discount", "cat": "Money"},
    {"ko": "가게", "pron": "gage", "en": "store, shop", "cat": "Places & things", "img": "shop"},
    {"ko": "시장", "pron": "sijang", "en": "market", "cat": "Places & things", "img": "market"},
    {"ko": "백화점", "pron": "baekhwajeom", "en": "department store", "cat": "Places & things"},
    {"ko": "편의점", "pron": "pyeonuijeom", "en": "convenience store", "cat": "Places & things"},
    {"ko": "옷", "pron": "ot", "en": "clothes", "cat": "Places & things", "img": "clothes"},
    {"ko": "신발", "pron": "sinbal", "en": "shoes", "cat": "Places & things", "img": "shoes"},
    {"ko": "가방", "pron": "gabang", "en": "bag", "cat": "Places & things", "img": "bag"},
    {"ko": "봉투", "pron": "bongtu", "en": "shopping bag", "cat": "Places & things"},
    {"ko": "사이즈", "pron": "saijeu", "en": "size", "cat": "Places & things"},
    {"ko": "사다", "pron": "sada", "en": "to buy", "cat": "Verbs & adjectives"},
    {"ko": "팔다", "pron": "palda", "en": "to sell", "cat": "Verbs & adjectives"},
    {"ko": "찾다", "pron": "chatda", "en": "to look for", "cat": "Verbs & adjectives"},
    {"ko": "비싸다", "pron": "bissada", "en": "to be expensive", "cat": "Verbs & adjectives", "img": "expensive"},
    {"ko": "싸다", "pron": "ssada", "en": "to be cheap", "cat": "Verbs & adjectives"},
    {"ko": "필요하다", "pron": "piryohada", "en": "to be needed", "cat": "Verbs & adjectives"},
    {"ko": "빨간색", "pron": "ppalgansaek", "en": "red", "cat": "Colors", "img": "red"},
    {"ko": "파란색", "pron": "paransaek", "en": "blue", "cat": "Colors", "img": "blue"},
    {"ko": "노란색", "pron": "noransaek", "en": "yellow", "cat": "Colors", "img": "yellow"},
    {"ko": "검은색", "pron": "geomeunsaek", "en": "black", "cat": "Colors", "img": "black"},
    {"ko": "흰색", "pron": "huinsaek", "en": "white", "cat": "Colors", "img": "white"},
    {"ko": "초록색", "pron": "choroksaek", "en": "green", "cat": "Colors", "img": "green"},
    {"ko": "분홍색", "pron": "bunhongsaek", "en": "pink", "cat": "Colors", "img": "pink"},
    {"ko": "좀 깎아 주세요", "pron": "jom kkakka juseyo", "en": "please give me a discount", "cat": "Phrases"},
    {"ko": "카드 돼요?", "pron": "kadeu dwaeyo?", "en": "Do you take cards?", "cat": "Phrases"},
    {"ko": "이거 살게요", "pron": "igeo salgeyo", "en": "I'll take this", "cat": "Phrases"},
    {"ko": "뭐 찾으세요?", "pron": "mwo chajeuseyo?", "en": "What are you looking for?", "cat": "Phrases"},
    {"ko": "어서 오세요", "pron": "eoseo oseyo", "en": "welcome (shop greeting)", "cat": "Phrases"}
  ],
  "15": [
    {"ko": "가다", "pron": "gada", "en": "to go", "cat": "Verbs"},
    {"ko": "오다", "pron": "oda", "en": "to come", "cat": "Verbs"},
    {"ko": "보다", "pron": "boda", "en": "to see / watch", "cat": "Verbs"},
    {"ko": "마시다", "pron": "masida", "en": "to drink", "cat": "Verbs", "img": "drink"},
    {"ko": "배우다", "pron": "baeuda", "en": "to learn", "cat": "Verbs"},
    {"ko": "만나다", "pron": "mannada", "en": "to meet", "cat": "Verbs"},
    {"ko": "먹다", "pron": "meokda", "en": "to eat", "cat": "Verbs"},
    {"ko": "읽다", "pron": "ikda", "en": "to read", "cat": "Verbs"},
    {"ko": "받다", "pron": "batda", "en": "to receive", "cat": "Verbs"},
    {"ko": "앉다", "pron": "anda", "en": "to sit", "cat": "Verbs"},
    {"ko": "사다", "pron": "sada", "en": "to buy", "cat": "Verbs"},
    {"ko": "자다", "pron": "jada", "en": "to sleep", "cat": "Verbs"},
    {"ko": "일어나다", "pron": "ireonada", "en": "to get up", "cat": "Verbs"},
    {"ko": "기다리다", "pron": "gidarida", "en": "to wait", "cat": "Verbs"},
    {"ko": "보내다", "pron": "bonaeda", "en": "to send / spend (time)", "cat": "Verbs"},
    {"ko": "되다", "pron": "doeda", "en": "to become", "cat": "Verbs"},
    {"ko": "청소하다", "pron": "cheongsohada", "en": "to clean", "cat": "Verbs"},
    {"ko": "공부하다", "pron": "gongbuhada", "en": "to study", "cat": "Verbs"},
    {"ko": "좋다", "pron": "jota", "en": "to be good", "cat": "Adjectives", "img": "good"},
    {"ko": "재미있다", "pron": "jaemiitda", "en": "to be fun", "cat": "Adjectives"},
    {"ko": "피곤하다", "pron": "pigonhada", "en": "to be tired", "cat": "Adjectives"},
    {"ko": "어제", "pron": "eoje", "en": "yesterday", "cat": "Time Words"},
    {"ko": "그저께", "pron": "geujeokke", "en": "the day before yesterday", "cat": "Time Words"},
    {"ko": "어젯밤", "pron": "eojetbam", "en": "last night", "cat": "Time Words"},
    {"ko": "아까", "pron": "akka", "en": "a little while ago", "cat": "Time Words"},
    {"ko": "지난주", "pron": "jinanju", "en": "last week", "cat": "Time Words"},
    {"ko": "지난달", "pron": "jinandal", "en": "last month", "cat": "Time Words"},
    {"ko": "작년", "pron": "jangnyeon", "en": "last year", "cat": "Time Words"},
    {"ko": "전에", "pron": "jeone", "en": "ago / before", "cat": "Time Words"},
    {"ko": "주말", "pron": "jumal", "en": "weekend", "cat": "Time Words"},
    {"ko": "주말 잘 보냈어요?", "pron": "jumal jal bonaesseoyo?", "en": "Did you have a good weekend?", "cat": "Phrases"},
    {"ko": "뭐 했어요?", "pron": "mwo haesseoyo?", "en": "What did you do?", "cat": "Phrases"},
    {"ko": "밥 먹었어요?", "pron": "bap meogeosseoyo?", "en": "Did you eat? (greeting)", "cat": "Phrases"},
    {"ko": "아무것도 안 했어요", "pron": "amugeotdo an haesseoyo", "en": "I didn't do anything", "cat": "Phrases"},
    {"ko": "잘했어요", "pron": "jalhaesseoyo", "en": "Well done", "cat": "Phrases"}
  ],
  "16": [
    {"ko": "왼쪽", "pron": "oenjjok", "en": "left", "cat": "Places & positions", "img": "left"},
    {"ko": "오른쪽", "pron": "oreunjjok", "en": "right", "cat": "Places & positions", "img": "right"},
    {"ko": "근처", "pron": "geuncheo", "en": "nearby, vicinity", "cat": "Places & positions"},
    {"ko": "사이", "pron": "sai", "en": "between", "cat": "Places & positions"},
    {"ko": "건너편", "pron": "geonneopyeon", "en": "the other side, across", "cat": "Places & positions"},
    {"ko": "길", "pron": "gil", "en": "road, way", "cat": "Places & positions"},
    {"ko": "사거리", "pron": "sageori", "en": "intersection", "cat": "Places & positions"},
    {"ko": "신호등", "pron": "sinhodeung", "en": "traffic light", "cat": "Places & positions"},
    {"ko": "지하철", "pron": "jihacheol", "en": "subway", "cat": "Transport", "img": "subway"},
    {"ko": "버스", "pron": "beoseu", "en": "bus", "cat": "Transport", "img": "bus"},
    {"ko": "택시", "pron": "taeksi", "en": "taxi", "cat": "Transport", "img": "taxi"},
    {"ko": "기차", "pron": "gicha", "en": "train", "cat": "Transport"},
    {"ko": "비행기", "pron": "bihaenggi", "en": "airplane", "cat": "Transport"},
    {"ko": "자전거", "pron": "jajeongeo", "en": "bicycle", "cat": "Transport"},
    {"ko": "역", "pron": "yeok", "en": "station", "cat": "Transport", "img": "station"},
    {"ko": "정류장", "pron": "jeongnyujang", "en": "bus stop", "cat": "Transport", "img": "bus-stop"},
    {"ko": "공항", "pron": "gonghang", "en": "airport", "cat": "Transport", "img": "airport"},
    {"ko": "출구", "pron": "chulgu", "en": "exit", "cat": "Transport"},
    {"ko": "입구", "pron": "ipgu", "en": "entrance", "cat": "Transport"},
    {"ko": "환승", "pron": "hwanseung", "en": "transfer", "cat": "Transport"},
    {"ko": "교통카드", "pron": "gyotongkadeu", "en": "transit card", "cat": "Transport"},
    {"ko": "요금", "pron": "yogeum", "en": "fare", "cat": "Transport"},
    {"ko": "호선", "pron": "hoseon", "en": "subway line number", "cat": "Transport"},
    {"ko": "표", "pron": "pyo", "en": "ticket", "cat": "Transport", "img": "ticket"},
    {"ko": "타다", "pron": "tada", "en": "to ride, get on", "cat": "Verbs"},
    {"ko": "내리다", "pron": "naerida", "en": "to get off", "cat": "Verbs"},
    {"ko": "갈아타다", "pron": "garatada", "en": "to transfer, change lines", "cat": "Verbs"},
    {"ko": "걸리다", "pron": "geollida", "en": "to take (time)", "cat": "Verbs"},
    {"ko": "건너다", "pron": "geonneoda", "en": "to cross", "cat": "Verbs"},
    {"ko": "돌다", "pron": "dolda", "en": "to turn", "cat": "Verbs"},
    {"ko": "멀다", "pron": "meolda", "en": "to be far", "cat": "Verbs", "img": "far"},
    {"ko": "가깝다", "pron": "gakkapda", "en": "to be close", "cat": "Verbs", "img": "near"},
    {"ko": "어떻게 가요?", "pron": "eotteoke gayo?", "en": "How do I get there?", "cat": "Phrases"},
    {"ko": "얼마나 걸려요?", "pron": "eolmana geollyeoyo?", "en": "How long does it take?", "cat": "Phrases"},
    {"ko": "쭉 가세요", "pron": "jjuk gaseyo", "en": "go straight", "cat": "Phrases"},
    {"ko": "걸어서", "pron": "georeoseo", "en": "on foot", "cat": "Phrases"},
    {"ko": "여기서 세워 주세요", "pron": "yeogiseo sewo juseyo", "en": "please stop here", "cat": "Phrases"},
    {"ko": "실례합니다", "pron": "sillyehamnida", "en": "excuse me", "cat": "Phrases"}
  ],
  "17": [
    {"ko": "쉬다", "pron": "swida", "en": "to rest", "cat": "Verbs"},
    {"ko": "놀다", "pron": "nolda", "en": "to play / hang out", "cat": "Verbs"},
    {"ko": "만들다", "pron": "mandeulda", "en": "to make", "cat": "Verbs"},
    {"ko": "열다", "pron": "yeolda", "en": "to open", "cat": "Verbs"},
    {"ko": "살다", "pron": "salda", "en": "to live", "cat": "Verbs"},
    {"ko": "전화하다", "pron": "jeonhwahada", "en": "to phone", "cat": "Verbs"},
    {"ko": "여행하다", "pron": "yeohaenghada", "en": "to travel", "cat": "Verbs"},
    {"ko": "키우다", "pron": "kiuda", "en": "to raise (a pet)", "cat": "Verbs"},
    {"ko": "내다", "pron": "naeda", "en": "to pay (for)", "cat": "Verbs", "img": "money"},
    {"ko": "시작하다", "pron": "sijakhada", "en": "to start", "cat": "Verbs"},
    {"ko": "운동하다", "pron": "undonghada", "en": "to exercise", "cat": "Verbs"},
    {"ko": "이따가", "pron": "ittaga", "en": "in a little while", "cat": "Time Words"},
    {"ko": "나중에", "pron": "najunge", "en": "later", "cat": "Time Words"},
    {"ko": "내일", "pron": "naeil", "en": "tomorrow", "cat": "Time Words"},
    {"ko": "모레", "pron": "more", "en": "the day after tomorrow", "cat": "Time Words"},
    {"ko": "이번 주말", "pron": "ibeon jumal", "en": "this weekend", "cat": "Time Words"},
    {"ko": "다음 주", "pron": "daeum ju", "en": "next week", "cat": "Time Words"},
    {"ko": "다음 달", "pron": "daeum dal", "en": "next month", "cat": "Time Words"},
    {"ko": "내년", "pron": "naenyeon", "en": "next year", "cat": "Time Words"},
    {"ko": "언제", "pron": "eonje", "en": "when; sometime", "cat": "Time Words"},
    {"ko": "계획", "pron": "gyehoek", "en": "plan", "cat": "Nouns"},
    {"ko": "약속", "pron": "yaksok", "en": "appointment / promise", "cat": "Nouns"},
    {"ko": "여행", "pron": "yeohaeng", "en": "trip", "cat": "Nouns"},
    {"ko": "표", "pron": "pyo", "en": "ticket", "cat": "Nouns", "img": "ticket"},
    {"ko": "영화관", "pron": "yeonghwagwan", "en": "movie theater", "cat": "Nouns"},
    {"ko": "강아지", "pron": "gangaji", "en": "puppy", "cat": "Nouns"},
    {"ko": "뭐 하고 싶어요?", "pron": "mwo hago sipeoyo?", "en": "What do you want to do?", "cat": "Phrases"},
    {"ko": "뭐 할 거예요?", "pron": "mwo hal geoyeyo?", "en": "What are you going to do?", "cat": "Phrases"},
    {"ko": "제가 할게요", "pron": "jega halgeyo", "en": "I'll do it", "cat": "Phrases"},
    {"ko": "같이 갈까요?", "pron": "gachi galkkayo?", "en": "Shall we go together?", "cat": "Phrases"},
    {"ko": "같이 가요", "pron": "gachi gayo", "en": "Let's go together", "cat": "Phrases"},
    {"ko": "갑시다", "pron": "gapsida", "en": "Let's go (formal)", "cat": "Phrases"},
    {"ko": "놀러 가다", "pron": "nolleo gada", "en": "to go out for fun", "cat": "Phrases"},
    {"ko": "잘 먹을게요", "pron": "jal meogeulgeyo", "en": "Thanks for the meal (before)", "cat": "Phrases"},
    {"ko": "언제 밥 한번 먹어요", "pron": "eonje bap hanbeon meogeoyo", "en": "Let's eat together sometime", "cat": "Phrases"}
  ],
  "18": [
    {"ko": "취미", "pron": "chwimi", "en": "hobby", "cat": "Hobbies"},
    {"ko": "운동", "pron": "undong", "en": "exercise, sports", "cat": "Hobbies"},
    {"ko": "독서", "pron": "dokseo", "en": "reading", "cat": "Hobbies"},
    {"ko": "여행", "pron": "yeohaeng", "en": "travel", "cat": "Hobbies"},
    {"ko": "등산", "pron": "deungsan", "en": "hiking", "cat": "Hobbies", "img": "hike"},
    {"ko": "수영", "pron": "suyeong", "en": "swimming", "cat": "Hobbies", "img": "swim"},
    {"ko": "축구", "pron": "chukgu", "en": "soccer", "cat": "Hobbies", "img": "soccer"},
    {"ko": "야구", "pron": "yagu", "en": "baseball", "cat": "Hobbies"},
    {"ko": "요리", "pron": "yori", "en": "cooking", "cat": "Hobbies", "img": "cook"},
    {"ko": "사진", "pron": "sajin", "en": "photo", "cat": "Hobbies"},
    {"ko": "그림", "pron": "geurim", "en": "drawing, painting", "cat": "Hobbies"},
    {"ko": "춤", "pron": "chum", "en": "dance", "cat": "Hobbies", "img": "dance"},
    {"ko": "기타", "pron": "gita", "en": "guitar", "cat": "Hobbies"},
    {"ko": "노래", "pron": "norae", "en": "song", "cat": "Hobbies", "img": "sing"},
    {"ko": "치다", "pron": "chida", "en": "to play (instrument, racket sport)", "cat": "Hobby verbs"},
    {"ko": "타다", "pron": "tada", "en": "to ride", "cat": "Hobby verbs"},
    {"ko": "추다", "pron": "chuda", "en": "to dance", "cat": "Hobby verbs", "img": "dance"},
    {"ko": "찍다", "pron": "jjikda", "en": "to take (a photo)", "cat": "Hobby verbs"},
    {"ko": "그리다", "pron": "geurida", "en": "to draw", "cat": "Hobby verbs"},
    {"ko": "배우다", "pron": "baeuda", "en": "to learn", "cat": "Hobby verbs"},
    {"ko": "좋아하다", "pron": "joahada", "en": "to like", "cat": "Hobby verbs"},
    {"ko": "매일", "pron": "maeil", "en": "every day", "cat": "Frequency"},
    {"ko": "자주", "pron": "jaju", "en": "often", "cat": "Frequency"},
    {"ko": "가끔", "pron": "gakkeum", "en": "sometimes", "cat": "Frequency"},
    {"ko": "보통", "pron": "botong", "en": "usually", "cat": "Frequency"},
    {"ko": "거의 안", "pron": "geoui an", "en": "hardly ever", "cat": "Frequency"},
    {"ko": "주말", "pron": "jumal", "en": "weekend", "cat": "Frequency"},
    {"ko": "노래방", "pron": "noraebang", "en": "karaoke room", "cat": "Leisure culture"},
    {"ko": "찜질방", "pron": "jjimjilbang", "en": "Korean spa, bathhouse", "cat": "Leisure culture"},
    {"ko": "치맥", "pron": "chimaek", "en": "chicken and beer", "cat": "Leisure culture"},
    {"ko": "동호회", "pron": "donghohoe", "en": "hobby club", "cat": "Leisure culture"},
    {"ko": "대박", "pron": "daebak", "en": "amazing! (slang)", "cat": "Leisure culture"},
    {"ko": "저도요", "pron": "jeodoyo", "en": "me too", "cat": "Leisure culture"}
  ],
  "19": [
    {"ko": "수영하다", "pron": "suyeonghada", "en": "to swim", "cat": "Verbs", "img": "swim"},
    {"ko": "운전하다", "pron": "unjeonhada", "en": "to drive", "cat": "Verbs"},
    {"ko": "만들다", "pron": "mandeulda", "en": "to make", "cat": "Verbs"},
    {"ko": "읽다", "pron": "ikda", "en": "to read", "cat": "Verbs"},
    {"ko": "기다리다", "pron": "gidarida", "en": "to wait", "cat": "Verbs"},
    {"ko": "앉다", "pron": "anda", "en": "to sit", "cat": "Verbs"},
    {"ko": "찍다", "pron": "jjikda", "en": "to take (a photo)", "cat": "Verbs"},
    {"ko": "들어가다", "pron": "deureogada", "en": "to go in, enter", "cat": "Verbs"},
    {"ko": "열다", "pron": "yeolda", "en": "to open", "cat": "Verbs"},
    {"ko": "만지다", "pron": "manjida", "en": "to touch", "cat": "Verbs"},
    {"ko": "걱정하다", "pron": "geokjeonghada", "en": "to worry", "cat": "Verbs"},
    {"ko": "늦다", "pron": "neutda", "en": "to be late", "cat": "Verbs"},
    {"ko": "피우다", "pron": "piuda", "en": "to smoke", "cat": "Verbs"},
    {"ko": "맡기다", "pron": "matgida", "en": "to leave in someone's care", "cat": "Verbs"},
    {"ko": "잘하다", "pron": "jalhada", "en": "to be good at", "cat": "Ability"},
    {"ko": "못하다", "pron": "motada", "en": "to be bad at, can't do", "cat": "Ability"},
    {"ko": "수", "pron": "su", "en": "way, means, possibility", "cat": "Ability"},
    {"ko": "할 수 있어요", "pron": "hal su isseoyo", "en": "I can do it", "cat": "Ability"},
    {"ko": "할 수 없어요", "pron": "hal su eopseoyo", "en": "I can't do it", "cat": "Ability"},
    {"ko": "아직 잘 못해요", "pron": "ajik jal motaeyo", "en": "I'm not good yet", "cat": "Ability"},
    {"ko": "해야 해요", "pron": "haeya haeyo", "en": "I have to do it", "cat": "Rules & permission"},
    {"ko": "해야 돼요", "pron": "haeya dwaeyo", "en": "I have to do it", "cat": "Rules & permission"},
    {"ko": "해도 돼요?", "pron": "haedo dwaeyo?", "en": "May I do it?", "cat": "Rules & permission"},
    {"ko": "안 해도 돼요", "pron": "an haedo dwaeyo", "en": "You don't have to", "cat": "Rules & permission"},
    {"ko": "하면 안 돼요", "pron": "hamyeon an dwaeyo", "en": "You must not do it", "cat": "Rules & permission"},
    {"ko": "돼요", "pron": "dwaeyo", "en": "it's OK, allowed", "cat": "Rules & permission"},
    {"ko": "안 돼요", "pron": "an dwaeyo", "en": "not allowed, no", "cat": "Rules & permission"},
    {"ko": "앉으세요", "pron": "anjeuseyo", "en": "please sit", "cat": "Requests"},
    {"ko": "드세요", "pron": "deuseyo", "en": "please eat (honorific)", "cat": "Requests"},
    {"ko": "걱정하지 마세요", "pron": "geokjeonghaji maseyo", "en": "don't worry", "cat": "Requests"},
    {"ko": "천천히 말해 주세요", "pron": "cheoncheonhi malhae juseyo", "en": "please speak slowly", "cat": "Requests"},
    {"ko": "다시 한 번 말해 주세요", "pron": "dasi han beon malhae juseyo", "en": "please say it again", "cat": "Requests"},
    {"ko": "잠깐만 기다려 주세요", "pron": "jamkkanman gidaryeo juseyo", "en": "please wait a moment", "cat": "Requests"},
    {"ko": "도와주세요", "pron": "dowajuseyo", "en": "please help me", "cat": "Requests"},
    {"ko": "좀", "pron": "jom", "en": "a bit (request softener)", "cat": "Requests"},
    {"ko": "죄송하지만", "pron": "joesonghajiman", "en": "I'm sorry, but…", "cat": "Requests"}
  ],
  "20": [
    {"ko": "머리", "pron": "meori", "en": "head", "cat": "Body", "img": "head"},
    {"ko": "얼굴", "pron": "eolgul", "en": "face", "cat": "Body"},
    {"ko": "눈", "pron": "nun", "en": "eye", "cat": "Body", "img": "eye"},
    {"ko": "코", "pron": "ko", "en": "nose", "cat": "Body", "img": "nose"},
    {"ko": "귀", "pron": "gwi", "en": "ear", "cat": "Body", "img": "ear"},
    {"ko": "입", "pron": "ip", "en": "mouth", "cat": "Body", "img": "mouth"},
    {"ko": "목", "pron": "mok", "en": "neck, throat", "cat": "Body", "img": "throat"},
    {"ko": "어깨", "pron": "eokkae", "en": "shoulder", "cat": "Body"},
    {"ko": "팔", "pron": "pal", "en": "arm", "cat": "Body"},
    {"ko": "손", "pron": "son", "en": "hand", "cat": "Body", "img": "hand"},
    {"ko": "배", "pron": "bae", "en": "stomach, belly", "cat": "Body", "img": "stomach"},
    {"ko": "허리", "pron": "heori", "en": "lower back, waist", "cat": "Body"},
    {"ko": "다리", "pron": "dari", "en": "leg", "cat": "Body", "img": "leg"},
    {"ko": "무릎", "pron": "mureup", "en": "knee", "cat": "Body"},
    {"ko": "발", "pron": "bal", "en": "foot", "cat": "Body", "img": "foot"},
    {"ko": "발목", "pron": "balmok", "en": "ankle", "cat": "Body"},
    {"ko": "아프다", "pron": "apeuda", "en": "to hurt, be sick", "cat": "Symptoms"},
    {"ko": "열이 나다", "pron": "yeori nada", "en": "to have a fever", "cat": "Symptoms", "img": "fever"},
    {"ko": "기침", "pron": "gichim", "en": "cough", "cat": "Symptoms", "img": "cough"},
    {"ko": "콧물", "pron": "konmul", "en": "runny nose", "cat": "Symptoms", "img": "runny-nose"},
    {"ko": "감기에 걸리다", "pron": "gamgie geollida", "en": "to catch a cold", "cat": "Symptoms"},
    {"ko": "다치다", "pron": "dachida", "en": "to get hurt", "cat": "Symptoms"},
    {"ko": "피곤하다", "pron": "pigonhada", "en": "to be tired", "cat": "Symptoms"},
    {"ko": "병원", "pron": "byeongwon", "en": "hospital, clinic", "cat": "Clinic & pharmacy", "img": "hospital"},
    {"ko": "의사", "pron": "uisa", "en": "doctor", "cat": "Clinic & pharmacy", "img": "doctor"},
    {"ko": "약국", "pron": "yakguk", "en": "pharmacy", "cat": "Clinic & pharmacy", "img": "pharmacy"},
    {"ko": "약", "pron": "yak", "en": "medicine", "cat": "Clinic & pharmacy", "img": "medicine"},
    {"ko": "감기약", "pron": "gamgiyak", "en": "cold medicine", "cat": "Clinic & pharmacy"},
    {"ko": "처방전", "pron": "cheobangjeon", "en": "prescription", "cat": "Clinic & pharmacy", "img": "prescription"},
    {"ko": "내과", "pron": "naegwa", "en": "internal medicine clinic", "cat": "Clinic & pharmacy"},
    {"ko": "치과", "pron": "chigwa", "en": "dentist", "cat": "Clinic & pharmacy"},
    {"ko": "구급차", "pron": "gugeupcha", "en": "ambulance", "cat": "Clinic & pharmacy"},
    {"ko": "푹 쉬세요", "pron": "puk swiseyo", "en": "get plenty of rest", "cat": "Advice phrases"},
    {"ko": "무리하지 마세요", "pron": "murihaji maseyo", "en": "don't overdo it", "cat": "Advice phrases"},
    {"ko": "빨리 나으세요", "pron": "ppalli naeuseyo", "en": "get well soon", "cat": "Advice phrases"}
  ],
  "21": [
    {"ko": "덥다", "pron": "deopda", "en": "to be hot", "cat": "ㅂ & ㄷ irregulars", "img": "hot"},
    {"ko": "춥다", "pron": "chupda", "en": "to be cold", "cat": "ㅂ & ㄷ irregulars", "img": "cold"},
    {"ko": "돕다", "pron": "dopda", "en": "to help", "cat": "ㅂ & ㄷ irregulars"},
    {"ko": "곱다", "pron": "gopda", "en": "to be fine, lovely", "cat": "ㅂ & ㄷ irregulars"},
    {"ko": "맵다", "pron": "maepda", "en": "to be spicy", "cat": "ㅂ & ㄷ irregulars", "img": "spicy"},
    {"ko": "쉽다", "pron": "swipda", "en": "to be easy", "cat": "ㅂ & ㄷ irregulars"},
    {"ko": "어렵다", "pron": "eoryeopda", "en": "to be difficult", "cat": "ㅂ & ㄷ irregulars"},
    {"ko": "가깝다", "pron": "gakkapda", "en": "to be near", "cat": "ㅂ & ㄷ irregulars", "img": "near"},
    {"ko": "눕다", "pron": "nupda", "en": "to lie down", "cat": "ㅂ & ㄷ irregulars"},
    {"ko": "듣다", "pron": "deutda", "en": "to listen, hear", "cat": "ㅂ & ㄷ irregulars"},
    {"ko": "걷다", "pron": "geotda", "en": "to walk", "cat": "ㅂ & ㄷ irregulars"},
    {"ko": "묻다", "pron": "mutda", "en": "to ask", "cat": "ㅂ & ㄷ irregulars"},
    {"ko": "바쁘다", "pron": "bappeuda", "en": "to be busy", "cat": "ㅡ & 르 stems"},
    {"ko": "아프다", "pron": "apeuda", "en": "to hurt, be sick", "cat": "ㅡ & 르 stems"},
    {"ko": "예쁘다", "pron": "yeppeuda", "en": "to be pretty", "cat": "ㅡ & 르 stems"},
    {"ko": "쓰다", "pron": "sseuda", "en": "to write, use", "cat": "ㅡ & 르 stems"},
    {"ko": "크다", "pron": "keuda", "en": "to be big, tall", "cat": "ㅡ & 르 stems", "img": "big"},
    {"ko": "모르다", "pron": "moreuda", "en": "to not know", "cat": "ㅡ & 르 stems"},
    {"ko": "부르다", "pron": "bureuda", "en": "to sing, call", "cat": "ㅡ & 르 stems", "img": "sing"},
    {"ko": "빠르다", "pron": "ppareuda", "en": "to be fast", "cat": "ㅡ & 르 stems"},
    {"ko": "다르다", "pron": "dareuda", "en": "to be different", "cat": "ㅡ & 르 stems"},
    {"ko": "살다", "pron": "salda", "en": "to live", "cat": "ㄹ & ㅅ stems"},
    {"ko": "알다", "pron": "alda", "en": "to know", "cat": "ㄹ & ㅅ stems"},
    {"ko": "놀다", "pron": "nolda", "en": "to play, hang out", "cat": "ㄹ & ㅅ stems"},
    {"ko": "낫다", "pron": "natda", "en": "to get better, recover", "cat": "ㄹ & ㅅ stems"},
    {"ko": "짓다", "pron": "jitda", "en": "to build, make up", "cat": "ㄹ & ㅅ stems"},
    {"ko": "붓다", "pron": "butda", "en": "to swell, pour", "cat": "ㄹ & ㅅ stems"},
    {"ko": "어떻다", "pron": "eotteota", "en": "to be how", "cat": "ㅎ adjectives"},
    {"ko": "그렇다", "pron": "geureota", "en": "to be so, like that", "cat": "ㅎ adjectives"},
    {"ko": "빨갛다", "pron": "ppalgata", "en": "to be red", "cat": "ㅎ adjectives", "img": "red"},
    {"ko": "노랗다", "pron": "norata", "en": "to be yellow", "cat": "ㅎ adjectives", "img": "yellow"},
    {"ko": "하얗다", "pron": "hayata", "en": "to be white", "cat": "ㅎ adjectives", "img": "white"},
    {"ko": "입다", "pron": "ipda", "en": "to wear", "cat": "Regular look-alikes"},
    {"ko": "좁다", "pron": "jopda", "en": "to be narrow", "cat": "Regular look-alikes"},
    {"ko": "받다", "pron": "batda", "en": "to receive", "cat": "Regular look-alikes"},
    {"ko": "닫다", "pron": "datda", "en": "to close", "cat": "Regular look-alikes"},
    {"ko": "웃다", "pron": "utda", "en": "to laugh, smile", "cat": "Regular look-alikes"},
    {"ko": "씻다", "pron": "ssitda", "en": "to wash", "cat": "Regular look-alikes"},
    {"ko": "좋다", "pron": "jota", "en": "to be good", "cat": "Regular look-alikes", "img": "good"}
  ],
  "22": [
    {"ko": "날씨", "pron": "nalssi", "en": "weather", "cat": "Weather"},
    {"ko": "기온", "pron": "gion", "en": "temperature", "cat": "Weather"},
    {"ko": "비", "pron": "bi", "en": "rain", "cat": "Weather", "img": "rain"},
    {"ko": "눈", "pron": "nun", "en": "snow", "cat": "Weather", "img": "eye"},
    {"ko": "바람", "pron": "baram", "en": "wind", "cat": "Weather"},
    {"ko": "안개", "pron": "angae", "en": "fog", "cat": "Weather"},
    {"ko": "하늘", "pron": "haneul", "en": "sky", "cat": "Weather"},
    {"ko": "태풍", "pron": "taepung", "en": "typhoon", "cat": "Weather", "img": "typhoon"},
    {"ko": "미세먼지", "pron": "misemeonji", "en": "fine dust", "cat": "Weather"},
    {"ko": "장마", "pron": "jangma", "en": "monsoon season", "cat": "Weather"},
    {"ko": "일기예보", "pron": "ilgiyebo", "en": "weather forecast", "cat": "Weather"},
    {"ko": "우산", "pron": "usan", "en": "umbrella", "cat": "Weather", "img": "umbrella"},
    {"ko": "영하", "pron": "yeongha", "en": "below zero", "cat": "Weather"},
    {"ko": "덥다", "pron": "deopda", "en": "to be hot (weather)", "cat": "Describing words", "img": "hot"},
    {"ko": "춥다", "pron": "chupda", "en": "to be cold (weather)", "cat": "Describing words", "img": "cold"},
    {"ko": "무덥다", "pron": "mudeopda", "en": "to be hot and muggy", "cat": "Describing words"},
    {"ko": "따뜻하다", "pron": "ttatteutada", "en": "to be warm", "cat": "Describing words"},
    {"ko": "시원하다", "pron": "siwonhada", "en": "to be cool", "cat": "Describing words"},
    {"ko": "쌀쌀하다", "pron": "ssalssalhada", "en": "to be chilly", "cat": "Describing words"},
    {"ko": "맑다", "pron": "makda", "en": "to be clear, sunny", "cat": "Describing words", "img": "sunny"},
    {"ko": "흐리다", "pron": "heurida", "en": "to be cloudy", "cat": "Describing words"},
    {"ko": "습하다", "pron": "seupada", "en": "to be humid", "cat": "Describing words"},
    {"ko": "건조하다", "pron": "geonjohada", "en": "to be dry", "cat": "Describing words"},
    {"ko": "차갑다", "pron": "chagapda", "en": "to be cold (to touch)", "cat": "Describing words"},
    {"ko": "뜨겁다", "pron": "tteugeopda", "en": "to be hot (to touch)", "cat": "Describing words"},
    {"ko": "비가 오다", "pron": "biga oda", "en": "to rain", "cat": "Weather verbs", "img": "rain"},
    {"ko": "눈이 오다", "pron": "nuni oda", "en": "to snow", "cat": "Weather verbs"},
    {"ko": "바람이 불다", "pron": "barami bulda", "en": "to be windy", "cat": "Weather verbs"},
    {"ko": "계절", "pron": "gyejeol", "en": "season", "cat": "Seasons"},
    {"ko": "봄", "pron": "bom", "en": "spring", "cat": "Seasons", "img": "spring"},
    {"ko": "여름", "pron": "yeoreum", "en": "summer", "cat": "Seasons", "img": "summer"},
    {"ko": "가을", "pron": "gaeul", "en": "autumn", "cat": "Seasons", "img": "autumn"},
    {"ko": "겨울", "pron": "gyeoul", "en": "winter", "cat": "Seasons", "img": "winter"},
    {"ko": "벚꽃", "pron": "beotkkot", "en": "cherry blossom", "cat": "Seasons"},
    {"ko": "단풍", "pron": "danpung", "en": "autumn leaves", "cat": "Seasons"}
  ],
  "23": [
    {"ko": "그리고", "pron": "geurigo", "en": "and / and then", "cat": "Connecting Words"},
    {"ko": "그래서", "pron": "geuraeseo", "en": "so / therefore", "cat": "Connecting Words"},
    {"ko": "그러니까", "pron": "geureonikka", "en": "so / that's why", "cat": "Connecting Words"},
    {"ko": "하지만", "pron": "hajiman", "en": "but / however", "cat": "Connecting Words"},
    {"ko": "그런데", "pron": "geureonde", "en": "but / by the way", "cat": "Connecting Words"},
    {"ko": "때", "pron": "ttae", "en": "time / when", "cat": "Time Words"},
    {"ko": "전에", "pron": "jeone", "en": "before", "cat": "Time Words"},
    {"ko": "후에", "pron": "hue", "en": "after", "cat": "Time Words"},
    {"ko": "다음에", "pron": "daeume", "en": "next time / after", "cat": "Time Words"},
    {"ko": "방학", "pron": "banghak", "en": "school vacation", "cat": "Time Words"},
    {"ko": "늦다", "pron": "neutda", "en": "to be late", "cat": "Verbs & Adjectives"},
    {"ko": "바쁘다", "pron": "bappeuda", "en": "to be busy", "cat": "Verbs & Adjectives"},
    {"ko": "배고프다", "pron": "baegopeuda", "en": "to be hungry", "cat": "Verbs & Adjectives", "img": "hungry"},
    {"ko": "피곤하다", "pron": "pigonhada", "en": "to be tired", "cat": "Verbs & Adjectives"},
    {"ko": "시원하다", "pron": "siwonhada", "en": "to be cool / refreshing", "cat": "Verbs & Adjectives"},
    {"ko": "앉다", "pron": "anda", "en": "to sit", "cat": "Verbs & Adjectives"},
    {"ko": "기다리다", "pron": "gidarida", "en": "to wait", "cat": "Verbs & Adjectives"},
    {"ko": "가져가다", "pron": "gajyeogada", "en": "to take along", "cat": "Verbs & Adjectives"},
    {"ko": "닫다", "pron": "datda", "en": "to close", "cat": "Verbs & Adjectives"},
    {"ko": "끝나다", "pron": "kkeunnada", "en": "to end / finish", "cat": "Verbs & Adjectives"},
    {"ko": "물어보다", "pron": "mureoboda", "en": "to ask", "cat": "Verbs & Adjectives"},
    {"ko": "켜다", "pron": "kyeoda", "en": "to turn on", "cat": "Verbs & Adjectives"},
    {"ko": "출발하다", "pron": "chulbalhada", "en": "to depart / set off", "cat": "Verbs & Adjectives"},
    {"ko": "등산하다", "pron": "deungsanhada", "en": "to go hiking", "cat": "Verbs & Adjectives"},
    {"ko": "연락하다", "pron": "yeollakhada", "en": "to contact / get in touch", "cat": "Verbs & Adjectives"},
    {"ko": "우산", "pron": "usan", "en": "umbrella", "cat": "Nouns", "img": "umbrella"},
    {"ko": "창문", "pron": "changmun", "en": "window", "cat": "Nouns", "img": "window"},
    {"ko": "에어컨", "pron": "eeokeon", "en": "air conditioner", "cat": "Nouns"},
    {"ko": "도서관", "pron": "doseogwan", "en": "library", "cat": "Nouns"},
    {"ko": "늦어서 죄송해요", "pron": "neujeoseo joesonghaeyo", "en": "sorry I'm late", "cat": "Set Phrases"},
    {"ko": "도와주셔서 감사합니다", "pron": "dowajusyeoseo gamsahamnida", "en": "thank you for helping", "cat": "Set Phrases"},
    {"ko": "시간이 있으면", "pron": "sigani isseumyeon", "en": "if you have time", "cat": "Set Phrases"},
    {"ko": "바빠서요", "pron": "bappaseoyo", "en": "because I'm busy", "cat": "Set Phrases"}
  ],
  "24": [
    {"ko": "회사원", "pron": "hoesawon", "en": "office worker", "cat": "Jobs"},
    {"ko": "교사", "pron": "gyosa", "en": "teacher (job title)", "cat": "Jobs", "img": "teacher"},
    {"ko": "의사", "pron": "uisa", "en": "doctor", "cat": "Jobs", "img": "doctor"},
    {"ko": "간호사", "pron": "ganhosa", "en": "nurse", "cat": "Jobs", "img": "nurse"},
    {"ko": "변호사", "pron": "byeonhosa", "en": "lawyer", "cat": "Jobs"},
    {"ko": "경찰관", "pron": "gyeongchalgwan", "en": "police officer", "cat": "Jobs"},
    {"ko": "요리사", "pron": "yorisa", "en": "chef", "cat": "Jobs", "img": "chef"},
    {"ko": "공무원", "pron": "gongmuwon", "en": "civil servant", "cat": "Jobs"},
    {"ko": "대학생", "pron": "daehaksaeng", "en": "university student", "cat": "Jobs"},
    {"ko": "사장님", "pron": "sajangnim", "en": "company president / boss", "cat": "Workplace"},
    {"ko": "부장님", "pron": "bujangnim", "en": "department head", "cat": "Workplace"},
    {"ko": "과장님", "pron": "gwajangnim", "en": "section chief / manager", "cat": "Workplace"},
    {"ko": "회사", "pron": "hoesa", "en": "company", "cat": "Workplace", "img": "office"},
    {"ko": "회의", "pron": "hoeui", "en": "meeting", "cat": "Workplace", "img": "meeting"},
    {"ko": "회식", "pron": "hoesik", "en": "team dinner", "cat": "Workplace"},
    {"ko": "보고서", "pron": "bogoseo", "en": "report", "cat": "Workplace"},
    {"ko": "일하다", "pron": "ilhada", "en": "to work", "cat": "Verbs"},
    {"ko": "다니다", "pron": "danida", "en": "to attend, go regularly", "cat": "Verbs"},
    {"ko": "출근하다", "pron": "chulgeunhada", "en": "to go to work", "cat": "Verbs"},
    {"ko": "퇴근하다", "pron": "toegeunhada", "en": "to leave work", "cat": "Verbs"},
    {"ko": "야근하다", "pron": "yageunhada", "en": "to work overtime", "cat": "Verbs"},
    {"ko": "가르치다", "pron": "gareuchida", "en": "to teach", "cat": "Verbs"},
    {"ko": "배우다", "pron": "baeuda", "en": "to learn", "cat": "Verbs"},
    {"ko": "졸업하다", "pron": "joreophada", "en": "to graduate", "cat": "Verbs"},
    {"ko": "취직하다", "pron": "chwijikhada", "en": "to get a job", "cat": "Verbs"},
    {"ko": "되다", "pron": "doeda", "en": "to become", "cat": "Verbs"},
    {"ko": "초등학교", "pron": "chodeunghakgyo", "en": "elementary school", "cat": "School"},
    {"ko": "고등학교", "pron": "godeunghakgyo", "en": "high school", "cat": "School"},
    {"ko": "대학교", "pron": "daehakgyo", "en": "university", "cat": "School", "img": "university"},
    {"ko": "대학원", "pron": "daehagwon", "en": "graduate school", "cat": "School"},
    {"ko": "전공", "pron": "jeongong", "en": "major (field of study)", "cat": "School"},
    {"ko": "숙제", "pron": "sukje", "en": "homework", "cat": "School"},
    {"ko": "시험", "pron": "siheom", "en": "exam", "cat": "School"},
    {"ko": "학원", "pron": "hagwon", "en": "private academy", "cat": "School"},
    {"ko": "무슨 일 하세요?", "pron": "museun il haseyo?", "en": "What do you do?", "cat": "Phrases"},
    {"ko": "수고하셨습니다", "pron": "sugohasyeotseumnida", "en": "thank you for your hard work", "cat": "Phrases"},
    {"ko": "먼저 가 보겠습니다", "pron": "meonjeo ga bogetseumnida", "en": "I'll head out first", "cat": "Phrases"}
  ],
  "25": [
    {"ko": "크다", "pron": "keuda", "en": "to be big", "cat": "Describing Words", "img": "big"},
    {"ko": "작다", "pron": "jakda", "en": "to be small", "cat": "Describing Words", "img": "small"},
    {"ko": "비싸다", "pron": "bissada", "en": "to be expensive", "cat": "Describing Words", "img": "expensive"},
    {"ko": "싸다", "pron": "ssada", "en": "to be cheap", "cat": "Describing Words"},
    {"ko": "맵다", "pron": "maepda", "en": "to be spicy", "cat": "Describing Words", "img": "spicy"},
    {"ko": "길다", "pron": "gilda", "en": "to be long", "cat": "Describing Words"},
    {"ko": "짧다", "pron": "jjalda", "en": "to be short", "cat": "Describing Words"},
    {"ko": "멀다", "pron": "meolda", "en": "to be far", "cat": "Describing Words", "img": "far"},
    {"ko": "빨갛다", "pron": "ppalgata", "en": "to be red", "cat": "Describing Words", "img": "red"},
    {"ko": "검다", "pron": "geomda", "en": "to be black", "cat": "Describing Words", "img": "black"},
    {"ko": "따뜻하다", "pron": "ttatteuthada", "en": "to be warm", "cat": "Describing Words"},
    {"ko": "맛있다", "pron": "masitda", "en": "to be delicious", "cat": "Describing Words", "img": "delicious"},
    {"ko": "재미있다", "pron": "jaemiitda", "en": "to be fun / interesting", "cat": "Describing Words"},
    {"ko": "멋있다", "pron": "meositda", "en": "to be cool / stylish", "cat": "Describing Words"},
    {"ko": "인기 있다", "pron": "ingi itda", "en": "to be popular", "cat": "Describing Words"},
    {"ko": "좋아하다", "pron": "joahada", "en": "to like", "cat": "Verbs"},
    {"ko": "알다", "pron": "alda", "en": "to know", "cat": "Verbs"},
    {"ko": "찾다", "pron": "chatda", "en": "to look for / find", "cat": "Verbs"},
    {"ko": "배우다", "pron": "baeuda", "en": "to learn", "cat": "Verbs"},
    {"ko": "보다", "pron": "boda", "en": "than (comparison particle)", "cat": "Comparison Words"},
    {"ko": "더", "pron": "deo", "en": "more", "cat": "Comparison Words"},
    {"ko": "덜", "pron": "deol", "en": "less", "cat": "Comparison Words"},
    {"ko": "제일", "pron": "jeil", "en": "the most / number one", "cat": "Comparison Words"},
    {"ko": "가장", "pron": "gajang", "en": "the most (formal)", "cat": "Comparison Words"},
    {"ko": "만큼", "pron": "mankeum", "en": "as … as", "cat": "Comparison Words"},
    {"ko": "훨씬", "pron": "hwolssin", "en": "much (more)", "cat": "Comparison Words"},
    {"ko": "중에서", "pron": "jungeseo", "en": "among / between", "cat": "Comparison Words"},
    {"ko": "한번", "pron": "hanbeon", "en": "once / give it a try", "cat": "Useful Phrases"},
    {"ko": "먹어 보다", "pron": "meogeo boda", "en": "to try eating", "cat": "Useful Phrases"},
    {"ko": "입어 보다", "pron": "ibeo boda", "en": "to try on (clothes)", "cat": "Useful Phrases"},
    {"ko": "간 적이 있다", "pron": "gan jeogi itda", "en": "to have been (somewhere)", "cat": "Useful Phrases"},
    {"ko": "아는 사람", "pron": "aneun saram", "en": "someone I know", "cat": "Useful Phrases"},
    {"ko": "할 일", "pron": "hal il", "en": "things to do", "cat": "Useful Phrases"},
    {"ko": "제일 좋아하는", "pron": "jeil joahaneun", "en": "favorite", "cat": "Useful Phrases"}
  ],
  "26": [
    {"ko": "핸드폰", "pron": "haendeupon", "en": "cell phone", "cat": "Devices & Internet"},
    {"ko": "휴대폰", "pron": "hyudaepon", "en": "mobile phone", "cat": "Devices & Internet", "img": "mobile-phone"},
    {"ko": "컴퓨터", "pron": "keompyuteo", "en": "computer", "cat": "Devices & Internet", "img": "computer"},
    {"ko": "노트북", "pron": "noteubuk", "en": "laptop", "cat": "Devices & Internet"},
    {"ko": "인터넷", "pron": "inteonet", "en": "internet", "cat": "Devices & Internet"},
    {"ko": "와이파이", "pron": "waipai", "en": "Wi-Fi", "cat": "Devices & Internet"},
    {"ko": "비밀번호", "pron": "bimilbeonho", "en": "password", "cat": "Devices & Internet", "img": "password"},
    {"ko": "충전기", "pron": "chungjeongi", "en": "charger", "cat": "Devices & Internet", "img": "charger"},
    {"ko": "배터리", "pron": "baeteori", "en": "battery", "cat": "Devices & Internet"},
    {"ko": "화면", "pron": "hwamyeon", "en": "screen", "cat": "Devices & Internet", "img": "screen"},
    {"ko": "앱", "pron": "aep", "en": "app", "cat": "Devices & Internet"},
    {"ko": "동영상", "pron": "dongyeongsang", "en": "video", "cat": "Devices & Internet"},
    {"ko": "문자", "pron": "munja", "en": "text message", "cat": "Messaging"},
    {"ko": "전화", "pron": "jeonhwa", "en": "phone call", "cat": "Messaging"},
    {"ko": "전화번호", "pron": "jeonhwabeonho", "en": "phone number", "cat": "Messaging"},
    {"ko": "이메일", "pron": "imeil", "en": "email", "cat": "Messaging", "img": "email"},
    {"ko": "답장", "pron": "dapjang", "en": "reply", "cat": "Messaging"},
    {"ko": "카톡", "pron": "katok", "en": "KakaoTalk (message)", "cat": "Messaging"},
    {"ko": "단톡방", "pron": "dantokbang", "en": "group chat room", "cat": "Messaging"},
    {"ko": "이모티콘", "pron": "imotikon", "en": "emoticon, sticker", "cat": "Messaging"},
    {"ko": "걸다", "pron": "geolda", "en": "to make (a call)", "cat": "Verbs"},
    {"ko": "받다", "pron": "batda", "en": "to answer, receive", "cat": "Verbs"},
    {"ko": "끊다", "pron": "kkeunta", "en": "to hang up", "cat": "Verbs"},
    {"ko": "보내다", "pron": "bonaeda", "en": "to send", "cat": "Verbs"},
    {"ko": "찍다", "pron": "jjikda", "en": "to take (a photo)", "cat": "Verbs"},
    {"ko": "켜다", "pron": "kyeoda", "en": "to turn on", "cat": "Verbs"},
    {"ko": "끄다", "pron": "kkeuda", "en": "to turn off", "cat": "Verbs"},
    {"ko": "충전하다", "pron": "chungjeonhada", "en": "to charge", "cat": "Verbs"},
    {"ko": "검색하다", "pron": "geomsaekhada", "en": "to search", "cat": "Verbs"},
    {"ko": "여보세요", "pron": "yeoboseyo", "en": "hello (on the phone)", "cat": "Phrases"},
    {"ko": "잘 안 들려요", "pron": "jal an deullyeoyo", "en": "I can't hear you well", "cat": "Phrases"},
    {"ko": "다시 전화할게요", "pron": "dasi jeonhwahalgeyo", "en": "I'll call you back", "cat": "Phrases"},
    {"ko": "ㅋㅋㅋ", "pron": "keukeukeu", "en": "lol (informal)", "cat": "Phrases"}
  ],
  "27": [
    {"ko": "기쁘다", "pron": "gippeuda", "en": "to be glad", "cat": "Feelings"},
    {"ko": "슬프다", "pron": "seulpeuda", "en": "to be sad", "cat": "Feelings", "img": "sad"},
    {"ko": "행복하다", "pron": "haengbokhada", "en": "to be happy", "cat": "Feelings", "img": "happy"},
    {"ko": "무섭다", "pron": "museopda", "en": "to be scared, scary", "cat": "Feelings"},
    {"ko": "외롭다", "pron": "oeropda", "en": "to be lonely", "cat": "Feelings"},
    {"ko": "부끄럽다", "pron": "bukkeureopda", "en": "to be shy, embarrassed", "cat": "Feelings"},
    {"ko": "그립다", "pron": "geuripda", "en": "to miss, long for", "cat": "Feelings"},
    {"ko": "피곤하다", "pron": "pigonhada", "en": "to be tired", "cat": "Feelings"},
    {"ko": "심심하다", "pron": "simsimhada", "en": "to be bored", "cat": "Feelings"},
    {"ko": "속상하다", "pron": "soksanghada", "en": "to be upset", "cat": "Feelings"},
    {"ko": "설레다", "pron": "seolleda", "en": "to feel excited, flutter", "cat": "Feelings"},
    {"ko": "걱정되다", "pron": "geokjeongdoeda", "en": "to be worried", "cat": "Feelings", "img": "worried"},
    {"ko": "화나다", "pron": "hwanada", "en": "to get angry", "cat": "Feelings"},
    {"ko": "놀라다", "pron": "nollada", "en": "to be surprised", "cat": "Feelings"},
    {"ko": "기분", "pron": "gibun", "en": "mood, feeling", "cat": "Feelings"},
    {"ko": "친구", "pron": "chingu", "en": "friend", "cat": "Relationships", "img": "friend"},
    {"ko": "남자친구", "pron": "namjachingu", "en": "boyfriend", "cat": "Relationships"},
    {"ko": "여자친구", "pron": "yeojachingu", "en": "girlfriend", "cat": "Relationships"},
    {"ko": "사랑하다", "pron": "saranghada", "en": "to love", "cat": "Relationships"},
    {"ko": "사귀다", "pron": "sagwida", "en": "to date, go out with", "cat": "Relationships"},
    {"ko": "결혼하다", "pron": "gyeolhonhada", "en": "to marry", "cat": "Relationships"},
    {"ko": "헤어지다", "pron": "heeojida", "en": "to break up", "cat": "Relationships"},
    {"ko": "친하다", "pron": "chinhada", "en": "to be close (friends)", "cat": "Relationships"},
    {"ko": "선배", "pron": "seonbae", "en": "senior (school/work)", "cat": "Relationships"},
    {"ko": "후배", "pron": "hubae", "en": "junior (school/work)", "cat": "Relationships"},
    {"ko": "정", "pron": "jeong", "en": "deep affection, bond", "cat": "Relationships"},
    {"ko": "보고 싶어요", "pron": "bogo sipeoyo", "en": "I miss you", "cat": "Expressions"},
    {"ko": "힘내세요", "pron": "himnaeseyo", "en": "cheer up, hang in there", "cat": "Expressions"},
    {"ko": "걱정하지 마세요", "pron": "geokjeonghaji maseyo", "en": "don't worry", "cat": "Expressions"},
    {"ko": "잘했어요", "pron": "jalhaesseoyo", "en": "well done", "cat": "Expressions"},
    {"ko": "대단해요", "pron": "daedanhaeyo", "en": "that's impressive", "cat": "Expressions"},
    {"ko": "파이팅", "pron": "paiting", "en": "you can do it!", "cat": "Expressions"},
    {"ko": "다행이에요", "pron": "dahaengieyo", "en": "what a relief", "cat": "Expressions"},
    {"ko": "죄송합니다", "pron": "joesonghamnida", "en": "I'm sorry (formal)", "cat": "Expressions"},
    {"ko": "제 잘못이에요", "pron": "je jalmosieyo", "en": "it's my fault", "cat": "Expressions"}
  ],
  "28": [
    {"ko": "공항", "pron": "gonghang", "en": "airport", "cat": "Airport", "img": "airport"},
    {"ko": "비행기", "pron": "bihaenggi", "en": "airplane", "cat": "Airport"},
    {"ko": "여권", "pron": "yeogwon", "en": "passport", "cat": "Airport", "img": "passport"},
    {"ko": "출발", "pron": "chulbal", "en": "departure", "cat": "Airport"},
    {"ko": "도착", "pron": "dochak", "en": "arrival", "cat": "Airport"},
    {"ko": "탑승구", "pron": "tapseunggu", "en": "boarding gate", "cat": "Airport"},
    {"ko": "수하물", "pron": "suhamul", "en": "baggage", "cat": "Airport"},
    {"ko": "입국 심사", "pron": "ipguk simsa", "en": "immigration", "cat": "Airport"},
    {"ko": "환전", "pron": "hwanjeon", "en": "currency exchange", "cat": "Airport"},
    {"ko": "면세점", "pron": "myeonsejeom", "en": "duty-free shop", "cat": "Airport"},
    {"ko": "왕복", "pron": "wangbok", "en": "round-trip", "cat": "Airport"},
    {"ko": "편도", "pron": "pyeondo", "en": "one-way", "cat": "Airport"},
    {"ko": "예약하다", "pron": "yeyakhada", "en": "to reserve, book", "cat": "Hotel & Sightseeing"},
    {"ko": "여행하다", "pron": "yeohaenghada", "en": "to travel", "cat": "Hotel & Sightseeing"},
    {"ko": "관광객", "pron": "gwangwanggaek", "en": "tourist", "cat": "Hotel & Sightseeing"},
    {"ko": "관광지", "pron": "gwangwangji", "en": "tourist spot", "cat": "Hotel & Sightseeing"},
    {"ko": "입장료", "pron": "ipjangnyo", "en": "entrance fee", "cat": "Hotel & Sightseeing"},
    {"ko": "조식", "pron": "josik", "en": "breakfast (hotel)", "cat": "Hotel & Sightseeing", "img": "breakfast"},
    {"ko": "짐", "pron": "jim", "en": "luggage", "cat": "Hotel & Sightseeing", "img": "luggage"},
    {"ko": "박", "pron": "bak", "en": "night (counter)", "cat": "Hotel & Sightseeing"},
    {"ko": "무료", "pron": "muryo", "en": "free of charge", "cat": "Hotel & Sightseeing"},
    {"ko": "설날", "pron": "seollal", "en": "Lunar New Year", "cat": "Culture"},
    {"ko": "추석", "pron": "chuseok", "en": "Chuseok (harvest festival)", "cat": "Culture"},
    {"ko": "한글날", "pron": "hangeullal", "en": "Hangul Day", "cat": "Culture"},
    {"ko": "한복", "pron": "hanbok", "en": "traditional clothing", "cat": "Culture"},
    {"ko": "한옥", "pron": "hanok", "en": "traditional house", "cat": "Culture"},
    {"ko": "한류", "pron": "hallyu", "en": "Korean Wave", "cat": "Culture"},
    {"ko": "세배", "pron": "sebae", "en": "New Year's bow", "cat": "Culture"},
    {"ko": "사진 좀 찍어 주세요", "pron": "sajin jom jjigeo juseyo", "en": "please take a photo", "cat": "Phrases"},
    {"ko": "길을 잃었어요", "pron": "gireul ireosseoyo", "en": "I'm lost", "cat": "Phrases"},
    {"ko": "도와주세요", "pron": "dowajuseyo", "en": "please help me", "cat": "Phrases"},
    {"ko": "천천히 말해 주세요", "pron": "cheoncheonhi malhae juseyo", "en": "please speak slowly", "cat": "Phrases"},
    {"ko": "새해 복 많이 받으세요", "pron": "saehae bok mani badeuseyo", "en": "Happy New Year", "cat": "Phrases"}
  ]
};
